### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by tusharbhutt** [rgthree/rgthree-comfy#1]
I don't know who you are, but thank you so much for making these nodes, they make the ComfyUI much easier to use!

**Comment by Frozen-byte** [comment]
I have to second this!

Finally, widgets with UX/UI in mind! 
I enjoy the Seed-Button with 'recover last seed' a lot! This finally solved all the "Change seed after generation, plz fix" issues.

Also, an impulse that flew to my mind:
A slider-Element with a visible Knob! This would allow for some nice SDXL Workflows to make the "Switch to Refiner" easier.
