### ISSUE TITLE
[Bug] Duplicated options in context menu for `Context` and `Context Big` after refreshing

### ISSUE THREAD

**Issue by Suiranoil** [rgthree/rgthree-comfy#100]
After pressing refresh button on menu and right clicking on `Context` or `Context Big` node options for `Connections Layout` and `Convert To ...` are duplicating
Context:
![image](https://github.com/rgthree/rgthree-comfy/assets/45388086/e5f25b95-8ecc-4703-ac12-3e88f6124dbd)

Context Big:
![image](https://github.com/rgthree/rgthree-comfy/assets/45388086/83b347ca-3687-4db9-bb2f-0cd118085670)

**Comment by rgthree** [comment]
Thanks for the report. Looks like @comfyanonymous broke this last week with https://github.com/comfyanonymous/ComfyUI/commit/36e15f2507ee81e27140cf15ffcda40070968928

Should be able to find a workaround.
