### ISSUE TITLE
[Bug/Feature] `Reroute` node cannot be connected to `Primitive` node

### ISSUE THREAD

**Issue by Suiranoil** [rgthree/rgthree-comfy#101]
As title says, `Reroute` node cannot be connected to output of a `Primitive` node from ComfyUI

**Comment by rgthree** [comment]
Yea, Primitive nodes didn't work with ComfyUI's own Reroute nodes until a month ago (https://github.com/comfyanonymous/ComfyUI/commit/44265e081031a4647b295b32e7f6b77ab71c80c9).

I've added support and it looks like it works; I'm kind of surprised. I do see other code in ComfyUI that is looking [explicitly for only their Reroute](https://github.com/comfyanonymous/ComfyUI/blob/c6951548cfec64c28082e6560c69c59e32729c9c/web/extensions/core/widgetInputs.js#L458) and not any other reroutes, but it seems to work anyway. Maybe that's old.
