### ISSUE TITLE
[Feature Request] Inversion option to Repeater node

### ISSUE THREAD

**Issue by cafe-lait** [rgthree/rgthree-comfy#102]
First of all, thanks for the great node.
Also, I am not an English speaker, so I may not be able to see the usage instructions and help in every corner, and I apologize if I have missed something.
Regarding my request, is it possible to implement a repeater option that reverses status when relaying & repeating?
Or if it is possible to do the same with existing nodes.
In a node-A>relay>repeater>node-B configuration, I would expect B to change to the opposite status of A.

FastGroupsXX's toggleRestriction is a relatively close function, but it is only for grouped nodes, and there are cases where I want to enable multiple at the same time,
It seems somewhat different from my purpose.

**Comment by rgthree** [comment]
I've been thinking of something like this. Added properties to the RELAY node to set custom signals overriding the default.

So, when all of a Relay's inputs are muted, you could configure it to send an "ACTIVE" signal to a repeater (instead of mute), etc.

**Comment by cafe-lait** [comment]
Thank you for your prompt response!
I immediately updated the nodes and incorporated it into my workflow and successfully achieved my goal.
Your work has made ConmfyUI even more enjoyable!
