### ISSUE TITLE
Somewhere between explicit and implicit group muter/bypasser

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#103]
The Group Muter/Bypasser is basically a "global", ie. all groups within the workflow show up. What I'm looking for is a way to, with a single button, mute/bypass multiple nodes _explicitly_. This is partially so I can organize the workflow "dashboard" and group buttons near where they are used.

**Comment by rgthree** [comment]
You use a regular Fast Muter and connect a single Repeater to it, which will make a single toggle on Fast Muter.

You can the connect as many nodes’ outputs you want to that Repeater, and it’s mute/bypass/enable change will “repeat” to all connected inputs.

**Comment by ghostsquad** [comment]
Oh. I didn't know that. I still think maybe this could be reopened, as these kinds of workarounds are not always obvious or intuitive.
