### ISSUE TITLE
Image Comparer (rgthree) just adds the images to the preview strip at the bottom of the screen

### ISSUE THREAD

**Issue by ricperry** [rgthree/rgthree-comfy#106]
As title says. I'm using latest ComfyUI and rgthree custom node (as of 9 Jan 2024). firefox (121), chromium (MS Edge), and webkit (used to be Epiphany) browsers all behave the same way. I'm using Ubuntu 22.04. Mouse over the node after image a and b both arrive in the workflow doesn't do anything. (image below is just to show it doesn't work, I know this isn't the intended use case)
![image](https://github.com/rgthree/rgthree-comfy/assets/34995372/f0656513-3eba-4e3a-a981-f02243c37f91)

**Comment by rgthree** [comment]
I think ComfyUI doesn't automatically make it large enough, so the images were there, but they were 0 height. I'll have to make a default height a little larger so the images appear and users know they can make it bigger.
