### ISSUE TITLE
'NoneType' object has no attribute 'movedim'

### ISSUE THREAD

**Issue by UserWithLootsProblems** [rgthree/rgthree-comfy#11]
I am new to this so I don't understand what is the problem. Here is the error when I run stable diffusion:
![image](https://github.com/rgthree/rgthree-comfy/assets/143909187/85ef8575-26fb-4d2f-ab5a-191d65a339d1)
I was trying to load a workflow but when I got everything that I needed for it to run correctly it didn't work: 
![image](https://github.com/rgthree/rgthree-comfy/assets/143909187/f74a934b-1fcf-48ed-baec-29c8b1f30329) 
What is the reason for this problem and how can I fix this?

**Comment by rgthree** [comment]
This isn't from this repo's nodes, and I'm not familiar with the nodes you've pasted, but looking at the screenshot it looks like that Load Image Batch node is looking in C:\Video's (as `path`) for images to send to the Upscale Image node, and it looks like you either don't have a C:\Videos path on your system, or perhaps there's no images in there. Good luck!
