### ISSUE TITLE
Fast Groups... nodes cause VHS nodes to flicker

### ISSUE THREAD

**Issue by moon47usaco** [rgthree/rgthree-comfy#111]
Adding the Fast Groups nodes to a workflow with VHS nodes causes the video previews to flicker.

**Comment by rgthree** [comment]
Looks like a bug in VHS nodes. Specifically, this line: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/blob/b86c1f9f4516faccb83c8957f0516443596def6b/web/js/VHS.core.js#L477C14-L477C25

Fast Groups Muter/Bypasser is using ComfyUI/LiteGraph's built in bounding calculation to determine group nodes, but VHS is doing something funky at that line above when the app requests the nodes' bounding box (which is what Fast Groups Muter/Bypasser does often).

**Comment by rgthree** [comment]
Filed a bug for VHS @ https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/128
