### ISSUE TITLE
The latest update is reporting an error

### ISSUE THREAD

**Issue by klossm** [rgthree/rgthree-comfy#112]
This happens with only rgthree-comfy installed!
The following is the content of the error message：
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "L:\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "L:\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 173, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  File "L:\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 173, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  File "L:\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 173, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  File "\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 173, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  [Previous line repeated 992 more times]
RecursionError: maximum recursion depth exceeded

**Comment by rgthree** [comment]
Do you have an example workflow? I haven’t taken a look, but the error looks like you may have an accidental loop somewhere.

**Comment by klossm** [comment]
> Do you have an example workflow? I haven’t taken a look, but the error looks like you may have an accidental loop somewhere.

I'm using comfyui's default workflow, I only kept rgthree-comfy installed, which means I'm getting errors without using rgthree-comfy's nodes, and I'm making sure that I don't have any problems with comfyui!

**Comment by rgthree** [comment]
Hmm... I don't see any ComfyUI changes that would cause an issue, and can't reproduce locally, though rgthree-comfy does optimize a bunch of slow code in comfyui. You can turn it off via config.

1. The config is a json fil in the root of the custom nodes. You can create a file (if it doesn't exist) as `[comfyui]/custom_nodes/rgthree-comfy/rgthree_config.json`.
    - _(You can also copy the `rgthree_config.json.default` if you want.)_
2. At the very least, the file should have this to turn off the optimization:
    ```json
    {
      "patch_recursive_execution": false
    }
    ```
3. When you restart ComfyUI, you should only see the first message below, and **NOT** the second message:
    ```bash
    [rgthree] Loaded 20 exciting nodes.
    [rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing
        seems broken, change "patch_recursive_execution" to false in rgthree_config.json
    ```

Let me know if that works.

**Comment by klossm** [comment]
I did what you said and the error disappeared.

**Comment by rgthree** [comment]
Hmm.. that's weird. It shouldn't be happening and I haven't heard any other ppl having this issue, but I don't like that it's happened here...

- You say it happens without any other extensions/custom nodes too and on the default, cleared workflow? That would rule out another custom extension interfering.
- What is your OS/system? Are you running this as the portable version?
- How did you install ComfyUI?

**Comment by klossm** [comment]
My computer is Win10 22H2, I made sure to keep only the custom node rgthree-comfy and loaded the default node of comfyui for operation with workflow cleared, because I kept only rgthree-comfy for troubleshooting purposes, and I didn't get any error message from other custom nodes I installed before. The other custom nodes I installed before didn't give me any errors, so this time I just kept rgthree-comfy for troubleshooting purposes, and I didn't use the portable version of comfyui, I deployed comfyui myself.

Translated with www.DeepL.com/Translator (free version)

**Comment by klossm** [comment]
Perhaps there are some conflicting dependencies when installing other custom nodes that cause the，I'll reinstall comfyui to rule it out.

**Comment by rgthree** [comment]
It's almost as if your ComfyUI is initializing rgthree-comfy twice, and the second time is then patching the new method over the old again, pointing to itself. I have two questions if you wouldn't mind trying something out:

1. First, when you start ComfyUI, how many times do you see the "[rgthree] Loaded XX exciting nodes." message in the terminal?
2. Second, I've just made a change to ensure we only patch the old execution once. Can you pull the latest, turn back on the recursion from the `rgthree_config` and see if it works?

**Comment by klossm** [comment]
> It's almost as if your ComfyUI is initializing rgthree-comfy twice, and the second time is then patching the new method over the old again, pointing to itself. I have two questions if you wouldn't mind trying something out:
> 
> 1. First, when you start ComfyUI, how many times do you see the "[rgthree] Loaded XX exciting nodes." message in the terminal?
> 2. Second, I've just made a change to ensure we only patch the old execution once. Can you pull the latest, turn back on the recursion from the `rgthree_config` and see if it works?

I've pulled the latest rgthree。
Here's the information you need to enable comfyui and run the workflow.

[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json


[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json


Import times for custom nodes:
   0.0 seconds: L:/ComfyUI/custom_nodes\rgthree-comfy
   1.9 seconds: L:\ComfyUI\custom_nodes\rgthree-comfy

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Exception in thread Thread-1 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "L:\ComfyUI_windows_portable\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "L:/ComfyUI_windows_portable/ComfyUI/custom_nodes\rgthree-comfy\__init__.py", line 172, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 172, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 172, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 172, in rgthree_execute
    return self.old_execute(*args, **kwargs)
  [Previous line repeated 992 more times]
RecursionError: maximum recursion depth exceeded

**Comment by rgthree** [comment]
Ah, yea, so your install is pulling rgthree-comfy twice. You should only see all of that once, like:

```bash
[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Import times for custom nodes:
0.0 seconds: L:/ComfyUI/custom_nodes\rgthree-comfy
```

I see that the slashes in your message is slightly different, like:
```
0.0 seconds: L:/ComfyUI/custom_nodes\rgthree-comfy
1.9 seconds: L:\ComfyUI\custom_nodes\rgthree-comfy
```

Not sure why that would matter (FWIW, I'm running the portable on windows and all my extensions use the backslash when listed, like: "L:\ComfyUI\custom_nodes\rgthree-comfy").

So that's the issue you're having. It feels like something is happening in ComfyUI here.. I wonder if you add another custom node, does it also show up twice?

**Comment by klossm** [comment]
This is what is displayed when I run the custom node sdxl_prompt_styler alone，It shows 2 times, but it runs fine and doesn't report an error problem

Import times for custom nodes:
   0.0 seconds: L:/ComfyUI/custom_nodes\sdxl_prompt_styler
   0.0 seconds: L:\ComfyUI\custom_nodes\sdxl_prompt_styler

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by rgthree** [comment]
great! thanks for debugging
