### ISSUE TITLE
All reroute nodes rotate at once

### ISSUE THREAD

**Issue by SeanBannister** [rgthree/rgthree-comfy#114]
When rotating a reroute node all existing reroute nodes in the workflow also rotate, I'm under the impression from the Readme that this is a bug as it appears to be possible to rotate each node individually. Has anyone else experienced this?

**Comment by rgthree** [comment]
Wild, LiteGraph doesn't deep clone properties, so when you copy + paste a bunch of reroutes the array holding their connection layout was the same. Thanks for finding this.

**Comment by SeanBannister** [comment]
Just for reference, I even see this happen when I create new Reroute nodes on a blank workflow.

**Comment by rgthree** [comment]
Do you still see this if you pull the latest?

**Comment by SeanBannister** [comment]
Unfortunately I do still have the issue with the latest commit. I might try to strip down my install and see what's causing it but might take some time to until I get around to it.

**Comment by rgthree** [comment]
I found it. Similar issue as before, but on a default node. Please pull the latest and try again.

**Comment by SeanBannister** [comment]
There we go, that's the fix. Thanks so much for your work on this, appreciate it!!!
