### ISSUE TITLE
When jump to a Bookmark view the text box stay on the screen.

### ISSUE THREAD

**Issue by tuangd** [rgthree/rgthree-comfy#117]
I'm not sure this is ComfyUI bug or the Bookmark Bug. 
Because I found a similar issue in the ComfyUI repo (the text box stay open after collapsing node) but they said it's fixed. https://github.com/comfyanonymous/ComfyUI/issues/2378

So, I am going to report it here as it relate to the Bookmark function.

Pre jump with bookmark.
![Pre jump with bookmark](https://github.com/rgthree/rgthree-comfy/assets/8474403/61c83f90-9ff0-4ad6-b9f2-3f75c524cf0f)

After jump with bookmark
![After jump with bookmark](https://github.com/rgthree/rgthree-comfy/assets/8474403/e2139969-7fc7-4930-bec2-2a42f41fef42)

**Comment by rgthree** [comment]
Weird, this just started happening. Looks like it happens for non-rgthree nodes too (like the regular ClipTextEncode and Note, etc).

I filed https://github.com/comfyanonymous/ComfyUI/issues/2568 with comfyui.

**Comment by rgthree** [comment]
Actually, looks like it's due to https://github.com/Trung0246/ComfyUI-0246/issues/22. Closing this here.
