### ISSUE TITLE
Nodes are not loading properly

### ISSUE THREAD

**Issue by ffiras** [rgthree/rgthree-comfy#119]
This 2 nodes are not loading for me : 
Mute / Bypass Repeater
Fast Actions Button

![CUI](https://github.com/rgthree/rgthree-comfy/assets/23510025/ed63f7f9-1317-40c6-a0f1-88fa78a3d43f)

I've tried to update/install both manually and with the manager extension without any success.

**Comment by rgthree** [comment]
Do you see an error in the terminal when comfy-ui starts up or dev console?

**Comment by rgthree** [comment]
Odd.. I just installed those nodes and rgthree-comfy still seems to load fine. Glad it's resolved now.
