### ISSUE TITLE
Convert a rerouter to Reroute by rgthree

### ISSUE THREAD

**Issue by KINGLIFER** [rgthree/rgthree-comfy#122]
Is there a way to do this? For me to do this in the workflow I have will take too long to bother. The problem is the rerouter out goes to a lot of nodes and there are a lot of these examples. One can not just relink simply.

**Comment by rgthree** [comment]
Yea, something can probably be added..

**Comment by rgthree** [comment]
There's now an rgthree-comfy item in the right-click context menu when clicking on the workflow background with an option to convert. Make sure to check connections afterwards, though... nothing is guaranteed in the world of ComfyUI.

![Screenshot 2024-01-19 225501](https://github.com/rgthree/rgthree-comfy/assets/476360/47c993df-9a66-4377-858e-3f57005cfae6)

**Comment by KINGLIFER** [comment]
A bit over kill but awesome. I think the best way would to have 2 options this and one that says Convert **selected** 'Reroute' => 'Reroute (rgthree)'

**Comment by rgthree** [comment]
Sure, why not. Still one item, but if you have nodes selected, then the _same_ option in the menu will change to convert any reroute nodes in the selected nodes instead of all reroute nodes.
