### ISSUE TITLE
[Feature Request]  "Wireless input"  option in Reroute node

### ISSUE THREAD

**Issue by AlexD81** [rgthree/rgthree-comfy#127]
Hi, Is it possible please, to add "Wireles input" option in  Reroute node, similar to another node based software - Blackmagic Fusion?
This would be most effective way to get rid of all spaghetties.

here's screenshot how does it looks in Fusion
https://snipboard.io/nUOjT5.jpg
And when you click on such "wireles reroute" node, the hidden link becomes visible, until node is selected.
Wireless reroute node ideally could be just small dot  with hidden input pipe

thanks beforehand

**Comment by AlexD81** [comment]
Not relevant anymore, because of this addon  https://github.com/mape/ComfyUI-mape-Helpers

**Comment by rgthree** [comment]
Nice, though I may suggest using the original https://github.com/chrisgoringe/cg-use-everywhere it’s harder to trust a custom node that doesn’t share their source client code (just the packed code), especially one that uses code from other open source projects.

**Comment by AlexD81** [comment]
> Nice, though I may suggest using the original https://github.com/chrisgoringe/cg-use-everywhere
Do you mean Highway nodes?  Need to try.  Concerning Mape addon for wireless links,  It's too buggy... And not too easy to use.   Still need someone who make addon for just rerouter node with hidden input,  that unhides when rerouter node is selected.

**Comment by rgthree** [comment]
No, the cg-use-anywhere has, essentially, wireless nodes. They aren’t reroutes, but they allow you to connect a type and “transmit” that type wirelessly to other nodes. You should check it out.
