### ISSUE TITLE
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None) from your Green BAR 

### ISSUE THREAD

**Issue by Soliver84** [rgthree/rgthree-comfy#129]
Hello BUG on Your BAR:

ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

**Comment by rgthree** [comment]
This doesn't look like anything to do with rgthree-comfy, or the bar. What gives you that impression? Is there a reproduction case?
