### ISSUE TITLE
[Function enhancement] `Queue Node (rgthree)` supports executing any number of output nodes

### ISSUE THREAD

**Issue by mijuku233** [rgthree/rgthree-comfy#132]
The `Queue Node (rgthree)` function is really great!
It would be better if it supports executing multiple outputs.

When there are multiple outputs in the workflow, select any number of output nodes.
Right-click and click on `Queue Node (rgthree)`, the selected output node will be executed, and the unselected one will not be executed.

**Comment by rgthree** [comment]
Makes sense. Added a persistent right-click item to queue any selected output nodes.
