### ISSUE TITLE
[ISSUE]Seed(rgthree) "Randomize Each Time" does not work

### ISSUE THREAD

**Issue by miurgh** [rgthree/rgthree-comfy#134]
Click "Randomize Each Time" (not "New Fixed Random")
↓
◀︎seed -1▶︎
↓
Click "Que Prompt"
↓
◀︎seed ***************▶︎

"-1" is not sustained.
Same results for "-2" and "-3".

**Comment by rgthree** [comment]
This happened before due to a conflict with another custom node/extension. What happens if rgthree-comfy is the only custom node?

**Comment by miurgh** [comment]
![スクリーンショット 2024-02-05 21 02 09](https://github.com/rgthree/rgthree-comfy/assets/147019070/b6fb9adc-6da9-4e7c-9160-252b378a33c9)
↓
Click "Que Prompt"
↓

![スクリーンショット 2024-02-05 21 00 52](https://github.com/rgthree/rgthree-comfy/assets/147019070/526528e0-ae10-4359-ad0a-85b2aa8601ea)

At first, the conflict was only with [Simple String Combine (WLSH)].
Then it stopped functioning altogether.

**Comment by rgthree** [comment]
Ah, unfortunately, if you see that message then the seed may not go back to "-1". Your prompt has an error because there's no output node and therefore it was never executed (the reset _back to_ -1 happens after the backend tells the front end it's handling the prompt).

It's an easy fix to fix this particular test workflow. If you connect each SEED output to a "Display Any (rgthree)" node, then there's a valid output node and the workflow should run correctly.

**Comment by miurgh** [comment]
I followed your instructions to create a simple workflow and it worked fine.
"-1", "-2", and "--3" all work.

My complex workflow does not work.
<img width="470" alt="スクリーンショット 2024-02-06 7 51 21" src="https://github.com/rgthree/rgthree-comfy/assets/147019070/8c8c474d-bd02-4be8-9b4b-c4f28291184f">
↓
Click "Que Prompt"
↓

<img width="464" alt="スクリーンショット 2024-02-06 7 51 25" src="https://github.com/rgthree/rgthree-comfy/assets/147019070/181e116b-92a7-41ec-b7ce-d7fec615692f">

During trial and error, it works temporarily, but I cannot report it because it is not reproducible.

**Comment by rgthree** [comment]
So, between your first and second screenshot above, it looks like the "Global Seed (Inspire)" node is _setting_ the "Seed (rgthree)" widget value; in screenshot 1 the Global Seed node's value is 3422522135 and in the second screenshot the "Seed (rgthree)" node's seed widget is then 3422522135.

I'm not sure how that Global Seed node is supposed to work, but it looks like it's pretty clearly setting the rgthree seed node (and the seed node below it).

My assumption is, even in the third and fourth, you have a Global Seed node somewhere else on your workflow, or another node that is interfering with the "Seed (rgthree)"

**Comment by miurgh** [comment]
I am reporting that I was ### generally able to reproduce the problem.

If [Use Everywhere (UE Nodes)] is valid,"-1" is not sustained.
If [Use Everywhere (UE Nodes)] is invalid,"-1" is sustained.

However, until the browser is refreshed, the previous situation persists. Furthermore, it may not be reflected until you change something in the settings of Seed(rgthree).Furthermore, this may be a mistake, as the behavior is sometimes unexplainable. I will continue to look into this.
