### ISSUE TITLE
Recursion error breaking generation (again)

### ISSUE THREAD

**Issue by revolvedai** [rgthree/rgthree-comfy#136]
Hello,

We have been trying to get rgthree running, and generations are broken (sits on idle). We have it working now for our servers by using an older version, but still seems like a non standard fix that will be broken by future git updates so opening an issue for visibility.

We have Linux servers running latest ComfyUI.

We fixed this previously by adding the rgthree_config.json file and changing the flag to false. As mentioned in https://github.com/rgthree/rgthree-comfy/issues/44 

However, now that config doesn't seem to load. It doesn't show the error message on boot, nor does it show the "Recursion" note on boot. It seems like it installs fine. However when you generate, you get the same recursion error.

If we need to update however, that issue will occur. So we would like to understand how to address this.

Error on generation:

> got prompt
> Exception in thread Thread-7 (prompt_worker):
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/rd/ComfyUI/main.py", line 111, in prompt_worker
>     e.execute(item[2], prompt_id, item[3], item[4])
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 209, in rgthree_execute
>     return self.rgthree_old_execute(*args, **kwargs)
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 209, in rgthree_execute
>     return self.rgthree_old_execute(*args, **kwargs)
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 209, in rgthree_execute
>     return self.rgthree_old_execute(*args, **kwargs)
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 209, in rgthree_execute
>     return self.rgthree_old_execute(*args, **kwargs)
>   [Previous line repeated 988 more times]
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/__init__.py", line 176, in rgthree_execute
>     if get_config_value('features.patch_recursive_execution') is True:
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/py/config.py", line 8, in get_config_value
>     return get_dict_value(RGTHREE_CONFIG, key)
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/py/utils.py", line 18, in get_dict_value
>     return get_dict_value(found, '.'.join(keys), default)
>   File "/opt/rd/ComfyUI/custom_nodes/rgthree-comfy/py/utils.py", line 14, in get_dict_value
>     keys = dict_key.split('.')
> RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by segalinc** [comment]
same here

**Comment by d8ahazard** [comment]
That's not what we're doing, at least I don't think so.

Below is our extra_model_paths.yaml file. Should the net_drive_user line be
removed?

local:
  loras: |
    /opt/rd/ComfyUI/models/lora/lora
    /opt/rd/ComfyUI/models/lora/lycoris
  upscale_models: |
    /opt/rd/ComfyUI/models/upscaling
  checkpoints: |
    /opt/rd/ComfyUI/models/Stable-diffusion
  controlnet: /opt/rd/ComfyUI/models/controlnet
net_drive_user:
  custom_nodes: /opt/rd/ComfyUI/custom_nodes

**Comment by rgthree** [comment]
If ComfyUI is evaluating it and loading custom_nodes twice then, yes, ComfyUI to load anything in custom_nodes twice will cause issues with several custom nodes.

That may not be what's happening. It's easy to tell if the issue is because custom nodes are loaded twice. 

When you start ComfyUI, you'll see something like this:

```
Import times for custom nodes:
0.0 seconds: /opt/rd/ComfyUI/custom_nodes/rgthree-comfy
```

If you see that "rgthree-comfy" line more than once, then all custom nodes are being loaded twice.

Additionally, further done, you'll see something like the following line which, also, you should only see once:

```
[rgthree] Loaded 30 exciting nodes.
```

**Comment by d8ahazard** [comment]
Nope, it's not being loaded twice. Just once. I removed the line from the model_paths just in case.

Oddly enough, when I fetched the latest version of the extension and did *not* include the additional rgthree_config.json with the bit disabling the recursion, it now works with no issues.

We originally disabled recursion because it was entirely breaking the app, but now it seems to be fine?

Odd.

**Comment by rgthree** [comment]
Good to hear. Recursion should not be breaking anyone's workflows (unless custom nodes are loaded twice, like in #112). There was a time when turning it off would fix it even for people who had loaded custom nodes twice, but that changed recently and it would have broken again for systems loading custom nodes more than once (which, no one should be doing, so it's actually a signal to their system).
