### ISSUE TITLE
RGthree new update caused context menus to disappear

### ISSUE THREAD

**Issue by Siraj-HM** [rgthree/rgthree-comfy#137]
The context menu in many nodes vanished after the latest rgthree update

**Comment by Siraj-HM** [comment]
https://github.com/rgthree/rgthree-comfy/assets/139066507/0ae413ea-abca-4a2a-8a82-11cdb9c6e8c6

**Comment by GalaxyTimeMachine** [comment]
I just found that the "load image" node doesn't have the menu option to open mask editor, either. I need my inpainting! :(

**Comment by Siraj-HM** [comment]
> I just found that the "load image" node doesn't have the menu option to open mask editor, either. I need my inpainting! :(

Disable rgthree as of now or roll back to previous version.

**Comment by GalaxyTimeMachine** [comment]
> > I just found that the "load image" node doesn't have the menu option to open mask editor, either. I need my inpainting! :(
> 
> Disable rgthree as of now or roll back to previous version.

Already rolled back to commit 584f62322a2d25d771fce321314ad35d8e6b5797, which resolves my problem until it's fixed.

**Comment by OliviaOliveiira** [comment]
Same issue, hoping for a fix!)

**Comment by alexbofa** [comment]
Yes, the same problem. Don't have `Convert ...` 
![image](https://github.com/rgthree/rgthree-comfy/assets/58225118/fc8c724b-279d-4f79-8556-3902e399a259)

**Comment by rgthree** [comment]
Thanks for the report, this should be fixed in the latest.
