### ISSUE TITLE
Convert to Input/Widget broken

### ISSUE THREAD

**Issue by K3nt3L** [rgthree/rgthree-comfy#142]
Since the last updates (can't say which one, just noticed today, but it's recent), I can't convert input/widget (all nodes). 
When I disable rgthree nodes, it works fine again.
With another instance, it works  : I guess some other (conflicted) custom nodes is the real issue.
Still searching the black sheep....

**Comment by dapa5900** [comment]
I have the same issue.

**Comment by rgthree** [comment]
Are you using the latest? There was a context-menu issue for a few hours, but it was resolved a few days ago.

**Comment by dapa5900** [comment]
I've went to vacation afterwards and will be back at work tomorrow. Will
check it immediately, good to hear it has been resolved. Thanks!

Regis Gaughan, III ***@***.***> schrieb am So., 11. Feb.
2024, 04:21:

**Comment by dapa5900** [comment]
I've went to vacation afterwards and will be back at work tomorrow. Will check it immediately, good to hear it has been resolved. Thanks!

**Comment by K3nt3L** [comment]
After an update of the nodes, it's working again. 

Thanks
