### ISSUE TITLE
[Feature Request] select checkpoints via file browser 

### ISSUE THREAD

**Issue by JorgeR81** [rgthree/rgthree-comfy#143]
It would be nice to have a custom checkpoint loader node that allows you to select checkpoints via file browser ( like the image loader node ).

This would be useful for people that have lots of models, since the drop down list on the native checkpoint loader can get very long.

But the main advantage for me, would be to load checkpoints from multiple drives.

My main drive is only 512 GB, and SDXL checkpoints are very large.
I have another internal 512 GB SSD where I keep images and checkpoints used less often.

But to use these other checkpoints I have to delete checkpoints on my main drive, because I want to keep a decent amount of free space, which is very inconvenient. 

I'm not sure why Comfy UI does not work like this by default. 
It may not be technically possible ? 
Or is it just to prevent user error, when selecting the files ?

If possible, this would be one of the best Comfy UI usability improvements, given the large size of the models we need. 

Thanks

**Comment by JorgeR81** [comment]
I've just found that loading models from another drive it's already possible, by editing the [ extra_model_paths.yaml ]

https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

Instructions are in this discussion: 
https://github.com/comfyanonymous/ComfyUI/discussions/72

This solves the main problem for me.

But if you have any ideas on how to improve those massive drop down lists, you can keep this open.

**Comment by rgthree** [comment]
Yea, I was thinking about this earlier. Yes, `extra_model_paths.yaml` is how ComfyUI expects you to handle this situation, though I do think a file explorer would be much easier.

Unfortunately, I think ComfyUI expects everything to be in/relative to the paths in `extra_model_paths.yaml` when its handling the path values, so a File Explorer would likely be too incompatible.

Subfolders was my next idea too, but if other popular extensions already handle it, I think I'll just leave it to them... unless I could get it in the standard menu so we don't have to use special nodes...

**Comment by JorgeR81** [comment]
I heard that the extension developer ( pythongosssss ) was working at Stability AI now.
So, I guess he will end up adding this, if it does not complicate the native code too much.

The native loader is already able to recognize when a model is in a folder, which is helpful ( e.g. SDXL folder ).

![cpl](https://github.com/rgthree/rgthree-comfy/assets/72734038/8d1b8a82-2e4a-441b-bee8-f0d8eeb600a0)

**Comment by rgthree** [comment]
I added a feature just now to do it globally over all combo lists. It's off by default since I can't test all possible combos easily, but give it should work well for this Load Checkpoint case.

Turn it on in the rgthree-comfy settings (right-click on an empty portion and choose "rgthree-comfy > Settings") by enabling "(Menu) Auto Nest Subdirectories". You can be my beta tester.

**Comment by JorgeR81** [comment]
This is awesome!

It seems to work for all native loaders.
Those custom nodes were just for checkpoints and loras.

This is very useful to keep all the original file names.   

It does not work for IPAdapter models, but it's OK, that's a custom node.

I have not tested all of these, but I will report if I find any issues. 
I'm on Windows 10. 

![vae](https://github.com/rgthree/rgthree-comfy/assets/72734038/c77f16a1-1af4-4ff1-8561-e83dfdc32979)

![ups](https://github.com/rgthree/rgthree-comfy/assets/72734038/fbf5d864-7a39-4c58-80f3-bee2334345f6)

![cnet](https://github.com/rgthree/rgthree-comfy/assets/72734038/bc211a5c-48f3-4017-83a7-0b1e94403e9d)

![ipa](https://github.com/rgthree/rgthree-comfy/assets/72734038/0b60ff18-3785-40dd-b44f-41744e4add96)

**Comment by rgthree** [comment]
Ah, I forgot to mention the logic. I only trigger it if there's more than 20 total items. So, that IPAdapter one may work, but since there's only 14 I figured it may not be useful.

WDYT, I can remove that restriction..

**Comment by JorgeR81** [comment]
Yes, having a limit is a good idea.
People may want to create folders, just to reorder the files, and also see all the files, if there are few of them.

But, maybe expose this option to the user, since you also have a way to input numeric values in your settings.
You probably already have some hidden limits for these input values, to prevent user error.

![set2](https://github.com/rgthree/rgthree-comfy/assets/72734038/7812ba78-481e-4f8d-a10c-073974165998)

**Comment by JorgeR81** [comment]
When I have this setting enabled, I can't change the [ sampler_name ], in the KSampler node, via click select in the dropdown list. 
I can only change it, via click select in the triangle arrows.
If I disable this setting, it all works again. 

This only happens for [ sampler_name ], not the other dropdown lists of the KSampler node
The [ sampler_name ] list also has a search field at the top, like the loader dropdown lists where subfolders are used.
Maybe this issue is related to that ?

![test](https://github.com/rgthree/rgthree-comfy/assets/72734038/baaa5b63-d53f-4f3e-a213-80713571ff56)

**Comment by rgthree** [comment]
Thanks for catching. Fixed and also added the threshold to the options to make it configurable from the UI.
