### ISSUE TITLE
Queue Node still working?

### ISSUE THREAD

**Issue by BenderBlender** [rgthree/rgthree-comfy#145]
Can not understand. Either I'm doing something wrong, or it's already stopped working (after the next comfi update).
I click on execute the process, but nothing happens. Please answer, because... The function is very useful and maybe I’m just doing something wrong somewhere?

![image](https://github.com/rgthree/rgthree-comfy/assets/116355906/c34d2361-16d2-4532-84ad-b42db1085f8c)

**Comment by BenderBlender** [comment]
Figured out what the problem was. the function does not work when using  [chrisgoringe/cg-use-everywhere](https://github.com/chrisgoringe/cg-use-everywhere) nodes

**Comment by rgthree** [comment]
Hmm.. interesting. I wonder why that is.

**Comment by BenderBlender** [comment]
Oh thanks! This would be very helpful!

**Comment by BenderBlender** [comment]
I also wanted to say thank you very much for the seed node. I use it everywhere to fix the current generation.
I even put together an experimental “workflow” based on them to save all stages of working on an image. Those. so that you can continue a new branch from anywhere

![image](https://github.com/rgthree/rgthree-comfy/assets/116355906/94169e06-a439-4703-a411-cbb48fcf3a72)

**Comment by rgthree** [comment]
Fixed this to work with cg-use-anywhere by moving the trimming logic to _after_ cg-use-anywhere currently does its hijacking.
