### ISSUE TITLE
on Stable Swaram UI , Cmfy UI, missing tcl8.6.12

### ISSUE THREAD

**Issue by Soliver84** [rgthree/rgthree-comfy#146]
Hello

on Stable Swaram UI, ComfyUI

Error occurred when executing CR Color Bars:

Can't find a usable init.tcl in the following directories:
C:/Matrix/Data/Assets/lib/tcl8.6 C:/Matrix/Data/Packages/ComfyUI/venv/lib/tcl8.6 C:/Matrix/Data/Packages/ComfyUI/lib/tcl8.6 C:/Matrix/Data/Packages/ComfyUI/venv/library C:/Matrix/Data/Packages/ComfyUI/library C:/Matrix/Data/Packages/ComfyUI/tcl8.6.12/library C:/Matrix/Data/Packages/tcl8.6.12/library

![image](https://github.com/rgthree/rgthree-comfy/assets/11579411/42287264-b620-4f52-b1d3-7c962abf53e8)

Is that from your package?

**Comment by rgthree** [comment]
No, this does not look related to rgthree-comfy
