### ISSUE TITLE
context node can no longer be moved or opened if saved in a workflow in closed state

### ISSUE THREAD

**Issue by MokkaBoss1** [rgthree/rgthree-comfy#15]
Hi,

I am a big fan of this node and use it extensively but I noticed this issue recently on a number of my workflows.

Can you check it?

thanks

MokkaBoss1

**Comment by rgthree** [comment]
Yea, there's a bug in ComfyUI's code. I filed it at https://github.com/comfyanonymous/ComfyUI/issues/1448

It's for any node that start starts collapsed and has this kind of input (not just my nodes and not just the context node). The good news is that I do have a fix, but it's a part of a much larger change bringing some awesome new feature to the nodes.

In the mean time, you can "unstick" them, but right clicking and selecting "collapse" from the ComfyUI node menu. That seems to fix the issue for Comfy.

**Comment by MokkaBoss1** [comment]
Hi,

many thanks for the workaround - I tried it and it works! Many thanks and I hope the underlying code gets fixed at some point.

Kind regards

MokkaBoss1

**Comment by rgthree** [comment]
Great. I actually have a fix for this, but it's grouped with a bunch of stuff on this repo's dev branch at https://github.com/rgthree/rgthree-comfy/tree/dev . Unfortunately, it requires some optimization in comfyui itself. Once https://github.com/comfyanonymous/ComfyUI/issues/1502 is fixed and/or https://github.com/comfyanonymous/ComfyUI/issues/1502 is merged, then this can land in rgthree/rgthree-comfy main.
