### ISSUE TITLE
Just to confirm, "RGthree seed" when using a latent batch WILL increment or randomize the seed, right? 

### ISSUE THREAD

**Issue by stephantual** [rgthree/rgthree-comfy#150]
Hyper simplified worflow for explanation:

I use 'new fixed random' - i get the same image everytime.
I use 'batch' in 'empty latent' - I get two images, but they aren't identical .

This leads me to think that internally, rgthree seed is 'intelligent enough' to detect my intention and increments the seed, or randomizes it somehow. If it's not a simple increment, is there a way to get the seed history from the batch? Thank you.

![ComfyUI_temp_izhkp_00010_](https://github.com/rgthree/rgthree-comfy/assets/1596070/480465b0-6acc-48db-8a0e-5a0fcb7f0a9c)

**Comment by rgthree** [comment]
The seed node’s input works similar to A111 and all that matters is what the input value is (the buttons just pre-set that input).

1. If the input is “-1” then the node will fill in a random seed when a prompt is queued (and then seamlessly re-set it to -1 for the next prompt).
2. These are more hidden, but if the value is -2 or -3 then the node will increment / decrement the last seed value respectively (and then seamlessly re-set it to -2 or -3 for the next prompt).
3. If the input is any other value then that value will be used as the seed, and stick.

The buttons just set the input. “New Fixed Random” generates a new random seed and sets the input to that. After that, the node behaves like number three above.

Now, when you batch several and get different images, that’s not the node generating different seeds. That’s just the way batching creates different noise, regardless of using my seed node or not.

I hope that helps and makes sense.

**Comment by stephantual** [comment]
Thank you so much - now I understand that it's batching creating different noise. I appreciate your help!
