### ISSUE TITLE
Display Any disables generation

### ISSUE THREAD

**Issue by CHollman82** [rgthree/rgthree-comfy#152]
Whenever I have a Display Any node in my workflow I can't even click the "Queue Prompt" button in Comfy. It's not that a get an error or anything... it seems like it just disables the button.

I've tried connecting it to different types of data such textual data, ints, and floats... it doesn't matter. In fact even if it's not connected to anything, just sitting on the graph isolated, it still breaks Comfy and prevents generating any images.

**Comment by rgthree** [comment]
Hmmm. Do you have an example workflow? I can't seem to reproduce this on my end.

Does the workflow have something to run? ComfyUI only executes a workflow when there's a change from the previous executed prompt (like a random seed, etc).

Also, if you open your browser's dev console, do you see any errors in the console when you try to run?

**Comment by CHollman82** [comment]
Sorry to bother you with this, I somehow got ComfyUI setup to not check for updates. After updating everything works again.
