### ISSUE TITLE
Feature request: multi image comparer

### ISSUE THREAD

**Issue by stephantual** [rgthree/rgthree-comfy#153]
I know it's cheeky to ask, but it would be really nice if the image comparer accepted image arrays. This way we could select which  tuple of image we wished to compare. Right now it only picks the first in the list, which makes it tricky when working with batches (specifically, i'm using preview chooser to interupt workflows mid-batch before doing anything GPU-heavy with the images, like ldsr :) - https://github.com/chrisgoringe/cg-image-picker/

Thank you!

**Comment by rgthree** [comment]
So, like if you feed a batch of two images into both we'll call BatchA into the first input, and a batch of two images we'll call BatchB into the second, you could compare BatchA's first image with BatchB's first image, or BatchA's second image with BatchB's second image?

**Comment by stephantual** [comment]
Hello RG!
Exactly that.  
That would be AMAZING given how much of a 'numbers' game this becomes once one moves away from 'just playing with it'. In the seed god we trust :)

**Comment by rgthree** [comment]
[c8603bc](https://github.com/rgthree/rgthree-comfy/commit/c8603bc24adb81a06c8132331c974d1e0266b6b3) adds support for `image_a` and `image_b` to optionally be batches of images and, if so, you can choose which item from A and which item from B are shown from quick labels above the comparison image itself.

**Comment by Erehr** [comment]
Can we get another node that accept batches but don't split the batch images into separate sides (ie. 1 2 3 instead of 1A 2A 3A | 1B 2B 3B)? This would work only on batches with the same amount of images I guess.
