### ISSUE TITLE
[Bug] Show UE-Links does not work for grouped nodes

### ISSUE THREAD

**Issue by karl-von-knecht** [rgthree/rgthree-comfy#160]
I can include an "Anything Everywhere?" node in a grouped node and it continues to work.
This is very nice, I always want to group the "Anything Everywhere?" node together with its source, because that reduces clutter a lot.
Sadly the "Show UE links" does not work for the grouped node. Also the target slots of of the "Anything Everywhere?" node are no longer highlighted as AE targets. 

![image](https://github.com/rgthree/rgthree-comfy/assets/123109169/3862a514-b78e-424d-80d2-6944690844d0)

![image](https://github.com/rgthree/rgthree-comfy/assets/123109169/bb313788-f82c-400b-ad6e-4911d990088b)

**Comment by rgthree** [comment]
I think you want to file an issue for UE over at https://github.com/chrisgoringe/cg-use-everywhere

**Comment by karl-von-knecht** [comment]
oh you are right. Sorry for bothering you!
