### ISSUE TITLE
Fast Muter/Bypasser, with toggleRestriction Max/Always One, when muted and unmuted, all options get enabled

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#175]
I have a Fast Muter inside a group. It's to manage ControlNet Preprocessors. It's in a group because I may not want that instance of controlnet to run at all. When I unmute the group, this node turns all options to "yes", despite the toggle restriction. Forcing me to click them all/most back over to "no".

Maybe there's a better way to handle this. I'm open to suggestions. Thanks!

![image](https://github.com/rgthree/rgthree-comfy/assets/903488/0120b69e-424e-4380-8c79-3bc899d253ad)
![image](https://github.com/rgthree/rgthree-comfy/assets/903488/f0d54029-4ae2-41a0-bdee-8f38419c5111)
![image](https://github.com/rgthree/rgthree-comfy/assets/903488/f838222e-c229-48ea-a10b-b625ab54b7ac)

**Comment by ghostsquad** [comment]
related to #171

**Comment by ghostsquad** [comment]
I found a workaround using the Repeater Node.

![image](https://github.com/rgthree/rgthree-comfy/assets/903488/9c7c6a76-35b9-4d28-8064-0eb84ab0177a)

**Comment by rgthree** [comment]
The `toggleRestriction` is only enforced when you actually toggle an item (by clicking on the toggle) and not if the nodes' modes are changed outside of the muter.

This is in the README and in the Node Help as well:
![Screenshot 2024-03-28 210856](https://github.com/rgthree/rgthree-comfy/assets/476360/60a49b49-6f6a-4973-bfa5-02ee1e3a603b)

All to say, when you change a group to "enabled" that has it all linked to the `Enable Processing?` Fast Muter, it's not that Fast Muter is just updating the status, it's not doing anything functionally. (Also, the mute/enable status of that Fast Muter itself also has no bearing on functionality).

I'm glad you found a workaround! I can't think of something else off the top of my head, tbh.
