### ISSUE TITLE
[QOL] Add directory nesting in the popout

### ISSUE THREAD

**Issue by SampleTexting** [rgthree/rgthree-comfy#177]
Currently the directory nesting looks like this:
![image](https://github.com/rgthree/rgthree-comfy/assets/155495184/1e3eefc3-127e-4c45-a570-3cf0791422c2)

Would it be possible to also add directory nesting for the popouts from this as well? An example of the folder structure would be:
1 Anime    >
>1 specific anime    >
>>5 Frieren    >
>>> loraname.safetensors

**Comment by rgthree** [comment]
I agree. Added the ability. Still experimental, check it out and let me know what you think.

**Comment by DrJKL** [comment]
Thank you!

**Comment by JorgeR81** [comment]
This works great!

It even adds models to the same sub-subfolder, from a different SSD, if I set an extra search path.

![rg3](https://github.com/rgthree/rgthree-comfy/assets/72734038/e809f0cd-58ac-42a9-a3d8-c56cf0810677)

**Comment by Koitenshin** [comment]
@rgthree Has this been broken recently, or can you tell me how to enable it? My folder structure has nested listings "SD1, SD2, SD3, SDXL" -> "TRAINED, MERGED" -> Checkpoint name and it looks like the first image instead of the last post.

"Auto Nest Subdirectories" is checked in the menu and "Threshold" is set to 1. It's not working properly, only the first nesting (SD1, etc) appears, then a long list of what is in those folders and subfolders.

**Comment by rgthree** [comment]
Looks like it's still working correctly for me. If you open the browser Dev Tools (Usually F12 key) do you see any errors when you open the menus? Which nodes are you using, is it all of them?

I wonder if there's a conflict with another node's code or something similar.

**Comment by Koitenshin** [comment]
This was on a clean install of ComfyUI with only your pack installed.
```
Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
prompt_service.js:117 'execution_start' fired before prompt was made.
(anonymous) @ prompt_service.js:117
api.js:157 Unhandled message: {"type": "execution_interrupted", "data": {"prompt_id": "edb47b69-4cf7-4ed0-bfd1-17d8675afa35", "node_id": "3", "node_type": "KSampler", "executed": ["20", "70", "61"], "timestamp": 1722737457805}} Error: Unknown message type execution_interrupted
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
25prompt_service.js:117 'execution_start' fired before prompt was made.
(anonymous) @ prompt_service.js:117
```

**Comment by rgthree** [comment]
Weird. Nothing there looks out of the ordinary. Can you paste a screenshot of it not working?

**Comment by Koitenshin** [comment]
Here you go, It's nested like the first image, but I really need the subdirectories working like Jorge's image.

![rgthree_recursive_nesting_bug](https://github.com/user-attachments/assets/255da95f-c383-40da-ba03-efc69be66f9b)

**Comment by rgthree** [comment]
Hmm.. looks like it should be working. Let's try this:

1. Add "#rgthree-dev" to the address bar, hit enter, and then also reload the page. (It should look like `127.0.0.1:8188/#rgthree-dev`)
2. Open the rgthree-comfy settings dialog, and at the bottom you should see "Log level for browser dev console." with a drop-down. 
3. Change the dropdown to `DEV` and click the Save button.
4. Might need to reload the page browser page too.
5. Now, open the Browser Dev Tools' Console again (F12).
6. And then open the menu, and a submenu.

Now, with the above, do you see any yellow/red logs in the console? Specifically, ones that start with "Skipping context menu auto nesting..." ?

**Comment by Koitenshin** [comment]
Sorry it took so long. This is what it came up with.

```
[rgthree][ContextMenuAutoNest] Nested folders found (6).
litegraph.core.js:13751 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
ContextMenu @ litegraph.core.js:13751
LiteGraph.ContextMenu @ contextMenuFilter.js:11
LiteGraph.ContextMenu @ invertMenuScrolling.js:18
LiteGraph.ContextMenu @ menu_auto_nest.js:106
LGraphCanvas.processNodeWidgets @ litegraph.core.js:10105
LGraphCanvas.processMouseDown @ litegraph.core.js:6098
LGraphCanvas.processMouseDown @ changeTracker.js:160
LGraphCanvas.processMouseDown @ simpleTouchSupport.js:93
LGraphCanvas.processMouseDown @ rgthree.js:250
LGraphCanvas.processMouseDown @ app.js:1009
litegraph.core.js:13752 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
ContextMenu @ litegraph.core.js:13752
LiteGraph.ContextMenu @ contextMenuFilter.js:11
LiteGraph.ContextMenu @ invertMenuScrolling.js:18
LiteGraph.ContextMenu @ menu_auto_nest.js:106
LGraphCanvas.processNodeWidgets @ litegraph.core.js:10105
LGraphCanvas.processMouseDown @ litegraph.core.js:6098
LGraphCanvas.processMouseDown @ changeTracker.js:160
LGraphCanvas.processMouseDown @ simpleTouchSupport.js:93
LGraphCanvas.processMouseDown @ rgthree.js:250
LGraphCanvas.processMouseDown @ app.js:1009
litegraph.core.js:13751 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
ContextMenu @ litegraph.core.js:13751
inner_onclick @ litegraph.core.js:13951
litegraph.core.js:13752 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by Koitenshin** [comment]
> Okay, looks like the LiteGraph in the new UI has changed pretty significantly. I filed a bug at [Comfy-Org/litegraph.js#75](https://github.com/Comfy-Org/litegraph.js/issues/75) but I'm now a bit more worried there are more changes that have caused regressions.

@rgthree is it possible the new changes caused the subdirectory popout to regress as well?
