### ISSUE TITLE
can not bypass controlnet 

### ISSUE THREAD

**Issue by bihailantian655** [rgthree/rgthree-comfy#178]
![workflow (6)](https://github.com/rgthree/rgthree-comfy/assets/35267721/502ba749-fd5d-4544-9276-fc20ba226775)
![workflow (5)](https://github.com/rgthree/rgthree-comfy/assets/35267721/f2a9c2c2-f59f-4c77-b67f-214ff998cdc1)

the only difference between these two  pic is whether or not to bypass a cnet  group .   here  is   one  more  pic  

![workflow (7)](https://github.com/rgthree/rgthree-comfy/assets/35267721/ac83b327-5fdd-47ce-a83e-14ccee60f542)

I don't think this is a fault with [rgthree-comfy] , but I am unsure who to report this issue to.

**Comment by rgthree** [comment]
There are a lot of things happening here, but you are right and there may be a bug to file in the [comfyanonymous](https://github.com/comfyanonymous/ComfyUI/issues) project.

But first, "the only difference between these two pics" is **not** just the bypassed cnet. There are tons of differences:
- The top image is passing the model through `FreeU_v2` and the bottom is not.
- The top image is using Efficiency Nodes KSampler, and the bottom is just using the bare KSampler
- The top image has a different seed, different cfg, different, scheduler, and a different number of steps than the bottom

Now, once you fix all those, there is still an issue with the bypassed "cnet" Group Node in the Group2. I guess ComfyUI doesn't fully bypass inputs/outputs of group nodes. Once I ungroup that, and bypass the regular `Apply ControlNet` node, it works as expected. Like this:

![workflow(14)](https://github.com/rgthree/rgthree-comfy/assets/476360/7bcb1b4c-ff29-43a5-bbdd-252a97d467c7)

That the bug you could create for the [comfyanonymous](https://github.com/comfyanonymous/ComfyUI/issues) project.

**Comment by bihailantian655** [comment]
![workflow (8)](https://github.com/rgthree/rgthree-comfy/assets/35267721/9fbd261f-cb2c-4d32-a196-8fff857216c6)

**Comment by bihailantian655** [comment]
> Now, once you fix all those, there is still an issue with the bypassed "cnet" Group Node in the Group2. I guess ComfyUI doesn't fully bypass inputs/outputs of group nodes. Once I ungroup that, and bypass the regular `Apply ControlNet` node, it works as expected. Like this:




I'm a bit puzzled.   what do you  mean  
ungroup that, and bypass the regular `Apply ControlNet` node   . 

using you  workflow , it did work normally. 

But when I tried to replicate  using  this  workflow  and bypass it , 

the same issue happened.

**Comment by bihailantian655** [comment]
not  working  for  bypass the regular Apply ControlNet node .   ( Apply ControlNet advanced   )

**Comment by rgthree** [comment]
The naming is a little confusing; but there's two different things here:

- There "Groups" which are the blue colored rectangles in your last workflow ("Group" and "Group2").
- Also, ComfyUI has "Group Nodes" which look like a single node in the UI that is actually "wrapping" several nodes together. These are fairly new.

Your two "cnet" nodes in your workflow are these "Group Nodes", which are clearly buggy. What I did to show that these are buggy was simply _ungroup_ them and run it as bypassed and it works as expected. You can ungroup by right-clicking and choosing "Convert to Nodes" menu item:

![Screenshot 2024-03-29 125551](https://github.com/rgthree/rgthree-comfy/assets/476360/9adf2a0f-9793-4a2f-af8d-4d06718b2e1f)

![Screenshot 2024-03-29 125531](https://github.com/rgthree/rgthree-comfy/assets/476360/9ba2bbdd-5eef-4cb9-8ef1-4eec448c5efe)

When you do that, you'll get the two nodes and you can see bypassing the _actual_ Apply ControlNet node then shows the same image as above.

As you mentioned in the first comment, this doesn't have anything to do with rgthree-comfy; it's an issue with ComfyUI's own Group Nodes. I think you should file a bug in the [comfyanonymous/ComfyUI](https://github.com/comfyanonymous/ComfyUI/issues) project that these are not working as intended.

**Comment by bihailantian655** [comment]
Thank you for your explanation. 
Now that I fully understand, 
I will try to report this bug   to  [comfyanonymous/ComfyUI]  project
