### ISSUE TITLE
Unable to use last queued seed for -1 seeds when importing workflows

### ISSUE THREAD

**Issue by mizukarada** [rgthree/rgthree-comfy#18]
So the seed is actually present in the json workflow/image but when I load it onto the canvas, the last queued seed button is greyed out.

This is quite annoying, as I have to manually use external tools to look for the seed whenever I want to reproduce my image.

**Comment by rgthree** [comment]
When you load an image's workflow with the `Seed` node, your right that the `Last Queued Seed` button is grayed out; however, the `seed` input itself will be pre-filled with that images' seed.

So, in this screenshot I just dragged a generated image into comfy to load the workflow and, even though the seed was generated with "-1" the `Seed` node pre-fills the _actual seed_ of the image. So it should be ready to go.
![seed](https://github.com/rgthree/rgthree-comfy/assets/476360/f6ac2db9-4e43-48ab-8643-1e92d57621ad)

Are you experiencing something different?

**Comment by mizukarada** [comment]
@rgthree 

It's `-1` for me.

https://github.com/rgthree/rgthree-comfy/assets/111034657/817beb88-be81-4afa-a87c-2836b946c0a2

**Comment by rgthree** [comment]
Weird. I’ll check it out!

Which browser do you use?

**Comment by mizukarada** [comment]
I found the culprit. It was [ComfyUI_NestedNodeBuilder](https://github.com/ssitu/ComfyUI_NestedNodeBuilder). Seems like something in NNB is preventing the seed to be serialized properly because I can load workflows working as intended from a machine that has NNB disabled while I have NNB enabled on my main machine.

**Comment by rgthree** [comment]
Yea, looks like [ComfyUI_NestedNodeBuilder](https://github.com/ssitu/ComfyUI_NestedNodeBuilder) overwrites the `serializeValue` method for widgets which the Seed node here needs to own its serialization (since it needs to switch out the "-1" for the actual seed when it gets serialized).

You'll have to file a bug with that project; not sure why it stops serialization... looks like it may just be copy+paste from the original ComfyUI codebase.

**Comment by cliffrowley** [comment]
FYI I am seeing this issue now, and I don't have NestedNodeBuilder installed. I extracted the data from a PNG to check that the seed is actually present, and yes, it's there, but when I load the image into ComfyUI the RG Seed node says -1.

**Comment by rgthree** [comment]
Can you provide a workflow to help debug? @cliffrowley

**Comment by rgthree** [comment]
This actually looks like a new breaking change upstream from comfy. See #69 for a solution until it can be fixed.
