### ISSUE TITLE
[ Bug ] Groups collect nodes while being dragged, if Fast Groups Muter is used.

### ISSUE THREAD

**Issue by JorgeR81** [rgthree/rgthree-comfy#181]
What I mean, is that the outside nodes will be added to the group, and placed at random positions, where they made contact with the group ( e.g. see what happens if I drag the ControlNet2 group over ControlNet1 ).

I also had this issue with cg-use-everywhere, using group restrictions, but it's fixed now.

https://github.com/chrisgoringe/cg-use-everywhere/issues/175#issuecomment-2024364803

From the comments there, maybe you can apply the same fix !

![push](https://github.com/rgthree/rgthree-comfy/assets/72734038/68b06c09-4652-4aad-bbc0-3bf60a34fee5)

**Comment by rgthree** [comment]
Ha! I always thought that was happening on its own. Great, fixed.
