### ISSUE TITLE
[Feature] Exclude certain groups from Fast Groups Muter

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#186]
There are certain groups that never need muting. Still grouped because it enhances readability/organization. Was wondering if it would be possible to configure the Fast Groups Muter to ignore/exclude certain groups from showing up in it?

**Comment by JorgeR81** [comment]
Yes, it is !

With the `matchTitle` property can select the groups you want on the node. 
And with `customSortAlphabet` you can set the order they show up in the node.
And you can even have multiple Fast Groups Muter nodes for different types of groups !

![cp](https://github.com/rgthree/rgthree-comfy/assets/72734038/75653b59-ca8c-4d46-82ee-10cb073a9fa7)

**Comment by ghostsquad** [comment]
Oh! Nice. I didn't notice that in the properties! Closing! ♥️🍻🎉
