### ISSUE TITLE
[ Feature ] Add clip and model weights to the Power Lora Loader

### ISSUE THREAD

**Issue by JorgeR81** [rgthree/rgthree-comfy#191]
The new Power Lora Loader is a great idea !

Is it possible to incorporate individual clip and model weights, to this new design ? 

I think they would look good side by side, with the variable name next to the value, e.g.:

 < clip 1.00 >  < model 1.00 >

![pl](https://github.com/rgthree/rgthree-comfy/assets/72734038/52636f5a-bf85-4244-ad02-b1da9545fa36)

**Comment by rgthree** [comment]
Yes! I plan to do this, you're using the first version :)

**Comment by rgthree** [comment]
You can now change to a single strength, or a dual model & clip from the node Properties!

**Comment by JorgeR81** [comment]
Looks great.
I like the top line, with the text and the toggle all button. 

But  since the objective is also more compact design, could you add an option to hide the [ + Add Lora ] button.
If hidden, the loras could be added  via right click menu instead.

Alternatively you could make a  smaller  [ + Add Lora ] buttom and put it the top line.

![mk0](https://github.com/rgthree/rgthree-comfy/assets/72734038/e1a1bb7d-f58e-4620-8c4a-d6af439b3a8b)
