### ISSUE TITLE
Do the seed and KSampler Config nodes conflict with Anything Everywhere?

### ISSUE THREAD

**Issue by Gileanxxx** [rgthree/rgthree-comfy#192]
![screenshot-1712711274200](https://github.com/rgthree/rgthree-comfy/assets/163095612/952bffac-ac17-4794-b60b-535558424873)
After I created a new seed node in the new workflow, I wanted to combine it with Anything Everywhere, but it didn't work. However, the strange thing is that I copied the seed node from the old workflow and it ran normally. I found that for the same seed node, the new and old output parameters are different. What's going on? Also having the same problem is the KSampler Config node.

**Comment by JorgeR81** [comment]
Try the AE? node, with the input_regex.
Normally it's what I use. 

I've updated on April 7th.
I have the new Power Lora Loader node. 
But I'm not sure if I have the latest update about the seed node. 

The regular AE node it's also working for me. 

![rg3b](https://github.com/rgthree/rgthree-comfy/assets/72734038/b5c1e30e-6d85-43d4-b668-ad84ba37a9a8)

![rg3](https://github.com/rgthree/rgthree-comfy/assets/72734038/677b670b-4130-4ed0-923f-1175c0fd193c)

**Comment by Gileanxxx** [comment]
Sorry for replying only now. The problem has been solved. Thank you very much.
