### ISSUE TITLE
Installer issue.

### ISSUE THREAD

**Issue by pennyvc** [rgthree/rgthree-comfy#2]
Not a big issue. but when downloading the zip linked here. it saves out with the incorrect folder name, this throws errors with comfyui as it can't find the path it is trying to run. 
delete -main from the end and it fixes it.
thats if your installing it this way instead of following the instructions. btw :P

**Comment by rgthree** [comment]
Ah, makes sense. I've hardcoded the expect path  for git pull. This should now be fixed.  :)
