### ISSUE TITLE
[BUG] OPT_CONNECTION out-of-control proliferation in Fast Groups Muters/Bypassers groups

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#206]
Since the latest commit, every time I restart ComfyUI, the Fast Groups Muters/Bypassers "gain" a new OUT_CONNECTION output. 
This is the current situation :)

<img width="572" alt="Screenshot 2024-04-20 at 17 57 07" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/8f15b969-90f3-4111-99a4-ead74cefb8f3">

Thanks for looking into this.

P.s.: What does the OUT_CONNECTION do, by the way?

**Comment by rgthree** [comment]
Oops. Thanks for reporting. This is fixed and I've patched Groups Muter to trim back down to one.

> P.s.: What does the OUT_CONNECTION do, by the way?

OUT_CONNECTION really just let's you connect it to a Fast Actions Button node to let you toggle all on/off as part of it's button execution.

**Comment by alessandroperilli** [comment]
Super fast, as usual. Thank you!
