### ISSUE TITLE
Please tell me the use of the large files added after the update.

### ISSUE THREAD

**Issue by tanglup** [rgthree/rgthree-comfy#209]
![2f52](https://github.com/rgthree/rgthree-comfy/assets/160642431/fb44700f-4d44-47f5-a423-d0463d009630)

**Comment by DrJKL** [comment]
https://github.blog/2022-08-29-gits-database-internals-i-packed-object-store/

**Comment by tanglup** [comment]
> https://github.blog/2022-08-29-gits-database-internals-i-packed-object-store/

thank you
