### ISSUE TITLE
[BUG?] - Latest commit cause Queue menu items and ComfyUI Manager menu to misalign

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#220]
After installing the latest commit (which includes the new Label node), I noticed that various UI elements in both the Queue menu and in the ComfyUI Manager menu are misaligned:

<img width="1416" alt="Screenshot 2024-05-05 at 10 14 08" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/ee9ff04b-c205-4496-ae16-38ddbd7c66d1">

Disabling your custom node suite reverts to the usual look.

**Comment by JorgeR81** [comment]
The same happens to me. 
It looks like this, without the extra Queue menu customizations. 

![RG3](https://github.com/rgthree/rgthree-comfy/assets/72734038/76db80af-99f2-4f8a-9c1e-3751ddcb0b66)

**Comment by rgthree** [comment]
Thanks, fixed.

**Comment by alessandroperilli** [comment]
All back to normal. Thank you @rgthree for the very quick fix. 
But you should know that Context and Context Big nodes have restarted growing vertically, adding a lot of extra space at the bottom of the node. Not sure this is connected with their behaviour.
