### ISSUE TITLE
Power Loader Lora Missing

### ISSUE THREAD

**Issue by Mohsyn** [rgthree/rgthree-comfy#222]
I can not file power lora loader anywhere.

ComfyUI: 2149 \[059773\] (2024-04-28)
Manager: V2.24.1

``` 
... custom_nodes\rgthree-comfy>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean```

**Comment by JorgeR81** [comment]
Try updating all, via Manager.
I have it, and I'm on: 
```
ComfyUI-Manager (V2.26)
ComfyUI Revision: 2162 [565eb6d1] | Released on '2024-05-05'
```

![RG3](https://github.com/rgthree/rgthree-comfy/assets/72734038/f03f97fe-1381-4b42-9c95-66087bd70b26)

**Comment by Davikar** [comment]
Yeah, I have it too. It's on the bottom of my list. On the other hand, the Any Switch node is missing on the list, but I can find it if I use the search.

**Comment by Mohsyn** [comment]
> Yeah, I have it too. It's on the bottom of my list. On the other hand, the Any Switch node is missing on the list, but I can find it if I use the search.

updated all - it is still not showing in list but it does show in search. strange but works for me. 
Thanks everyone!
