### ISSUE TITLE
copy-paste Power Lora Loader settings loss bug

### ISSUE THREAD

**Issue by oO0** [rgthree/rgthree-comfy#224]
* fill some lora in Power Lora Loader 
* ctr-c, ctrl-v
* see settings is missing
copy with alt-drag is working but impossible to use for other browser page

**Comment by RamonGuthrie** [comment]
Same I wasn't sure if this was a bug, but it gets annoying every time I Copy and Paste (ctr-c, ctrl-v) I lose all my Loras and settings and have to load them all again

**Comment by rgthree** [comment]
I think this is fixed now. it was an accident, but I think I know what fixed it, so please check it out.
