### ISSUE TITLE
Bookmark node - Special character shortcut

### ISSUE THREAD

**Issue by joetcurrie** [rgthree/rgthree-comfy#227]
I created a large workflow which uses a lot of bookmark nodes. I used special characters for some of these nodes which used to work fine, but I think an update has removed that functionality. Is it possible to reintroduce as an option? 

For example I used to have the character 'Í' (option>shift>S) for my samplers group bookmark instead of 'S' which is used for the rgthree reroute node shortcut (shift+S).

**Comment by DrJKL** [comment]
@rgthree called it:https://github.com/rgthree/rgthree-comfy/pull/199#issuecomment-2067543706

**Comment by joetcurrie** [comment]
> @rgthree called it:[#199 (comment)](https://github.com/rgthree/rgthree-comfy/pull/199#issuecomment-2067543706)
Ah I see. Would a setting option for this be complicated to implement? 

Or perhaps allow shift + option keys but block command + ctrl? That would allow special characters and at the same time block copy/paste commands.

**Comment by DrJKL** [comment]
The code to ignore the events with modifier keys is super simple:
```ts
if (event.ctrlKey || event.metaKey || event.altKey) {
  return;
}
```

@rgthree Has also made a pretty easy [configuration system](https://github.com/rgthree/rgthree-comfy/blob/main/src_web/comfyui/config.ts) for settings.

That said, I'm generally wary of adding options. A good friend of mine likes to share [this article](https://neugierig.org/software/blog/2018/07/options.html) whenever someone asks to add a toggle or config. I usually stick to Latin characters, so it's definitely a blindspot.

`Option` on Mac OS is `Alt` on Windows, `event.altKey` above.

It might be safe to remove that from the guard, since the original issue was about Copying which would be `ctrlKey` on Windows, `metaKey` on Mac.

**Comment by rgthree** [comment]
Okay, so [f4eba67](https://github.com/rgthree/rgthree-comfy/commit/f4eba67933ccf05bb1afc44e2c95c7e618ea8126) added some work I had a while back that allows for more complex shortcuts. (Like "control + shift + s") if you wanted to.

However, it did change it to be an exclusive lookup, where the shortcut is only invoked if only those keys are pressed.

There isn't a fancy "press the key and it will show up in the input" experience so, @joetcurrie, you'll have to enter the shortcut in manually. I believe if you set the `short_cut` key to `alt + shift + Í` and it would work.

Please let me know if it works.

**Comment by joetcurrie** [comment]
Thanks for taking a look at this. I just tried the latest update. It seems now pressing `shift + alt` will jump to a bookmark node regardless of it being set in the `short_cut`. Does that replicate?

**Comment by rgthree** [comment]
Yup, just pushed a fix for the shift check. Please sync and try again :)

**Comment by joetcurrie** [comment]
Appreciate the quick action! Making the first bookmark node with `short_cut` `shift + alt + Í` works as intended. However changing a second bookmark node to `shift + alt +` (another special character) seems to break all bookmarks.

**Comment by rgthree** [comment]
Thanks. Also just added a better experience when inputting the shortcut. It will now enter the muiltiple keys you're pressing down.

(For example, clicking on `shortcut_key` widget brings up the same input popup. But now, pressing the shift key, the alt key, and the Í key, should show "SHIFT + ALT + Í" in the input automatically (order doesn't matter)

**Comment by joetcurrie** [comment]
Sorry to open this up again. I've noticed something strange happening with the bookmarks. Initially the shortcut key works, but it seems now that something gets stuck when using key combinations - for example if I copy and paste a node `cmd + `c`cmd + v` the bookmarks seem to think that the 'c' and 'v' key is still being pressed? This breaks the functionality of the bookmark until I repress those keys to unlock them.

**Comment by joetcurrie** [comment]
Sorry to open this up again. I have noticed that bookmark nodes now seem to get a sort of unintended sticky keys function when using modifier key combinations in comfyui. For example if I use `cmd + c` and `cmd + v` to copy and past a node, the bookmark nodes think that the C & V keys are still being pressed after they are released. Hopefully this video explains better. It seems to happen when using any combination of keys, similar function is seen when using cmd + enter to queue. 


https://github.com/rgthree/rgthree-comfy/assets/30127464/4e67a87f-156e-4bed-ae99-392f85f5fd1d
