### ISSUE TITLE
Feature request: Display Any node printing checkpoint name + passing inputs to other nodes

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#23]
As the title says: the new Display Any node is very useful for debugging, but it would be tremendously more useful if it would do two additional things:

1. Print the checkpoint name in the same way it does for the sampler name and the scheduler name. Right now, an attempt to link a Model output in a `Checkpoint Loader` node to the input of a `Display Any` node generates something like this: `<comfy.model_patcher.ModelPatcher object at 0x2d0f6b950>`

2. Pass any received input to other nodes. The printing within the node is much needed (I use the `ttn textDebug` for this, but it stopped printing the name inside the node weeks ago and it's not optimal). However, values like checkpoint name, sampler name, and scheduler name I'd like to print to terminal, concat with my labels, and save to files for various reasons.

Thanks!

**Comment by alessandroperilli** [comment]
Update on this: 

The first part of the request was related to #29, which has been addressed. So no need for it anymore.

The second part would be very nice to have, but I've found a way to achieve that with a combination of multiple 3rd party nodes. It's a lot more stuff than it could be, but it works.

So I'm going to close this request as it's not as urgent as it was before.

**Comment by rgthree** [comment]
1. I did look into displaying the model name from the model instance but, unfortunately, that doesn't seem to be available (the `model` instance is the loaded model in memory, but it doesn't know its name or path at that point).
2. I actually do have some work I may go back to for display any to pass along the value. I may get back to incorporating it into Display Any in the future.
