### ISSUE TITLE
SyntaxWarning

### ISSUE THREAD

**Issue by Nico53425342** [rgthree/rgthree-comfy#236]
D:\Desktop\Comfy-UI+EX\ComfyUI\custom_nodes\rgthree-comfy\py\power_prompt_utils.py:11: SyntaxWarning: invalid escape sequence '\d'
  pattern = '<lora:([^:>]*?)(?::(-?\d*(?:\.\d*)?))?>'

**Comment by Nico53425342** [comment]
problem solved

**Comment by Orenji-Tangerine** [comment]
How did you solve this?

**Comment by Orenji-Tangerine** [comment]
I notice that this happens only on Python 3.12, but not on 3.11 or 3.10...
