### ISSUE TITLE
REQEUST: A reroute node with randomizer & scaling input

### ISSUE THREAD

**Issue by Duemellon** [rgthree/rgthree-comfy#237]
Can there be a reroute that has a minimum of 2 inputs & will randomize which of the connected inputs goes through?

Here's a pic of KJNode's imagebatch that scales:

![image](https://github.com/rgthree/rgthree-comfy/assets/113479041/02ab2969-622e-4893-9f12-683422d7914f)

I tried this using Claude but it is missing some important part & won't produce the "update inputs" button & won't allow for any type of input (like a reroute does). I tried understanding your code but couldn't figure out what to feed ClaudeAI to process it properly so it would take any node input & put out that specific type. I assume there's a check/validation in there which identifies the type of data & update the node to use that type? 

The idea is to allow multiples of "same type" inputs to be randomized like models, or loras, or clips, or whatever but it only send one through.

Here was as far as I got. 

![image](https://github.com/rgthree/rgthree-comfy/assets/113479041/7c692847-fcb5-410f-9414-4e63169ecd64)

**Comment by rgthree** [comment]
I believe you can accomplish what you are looking for with the “Any Switch” and the “Random Unmuter”.

- Connect all your nodes to the any switch.
- Also, connect all your nodes to the Random Unmuter
- Make sure all your nodes start as muted.
- Execute your queue.


The Random Unmuter should unmute one of your nodes which will then be used by the Any Switch (which takes the first non-null input).

**Comment by Duemellon** [comment]
I'm having a hard time conceptualizing the use of the "muter". I'll look online to see if there are any tutorials about it. Sounds like it's useful in many ways. Same with that "fast actions" since I would like to have randomization within a batch to compare instead of having the same queue'd batch churn out the same.

**Comment by Duemellon** [comment]
Whew... I didn't know about the "mute" feature. The only way I can get it to go is keyboard shortcut Ctl+M but that did the trick! thanks.
