### ISSUE TITLE
[FEATURE REQUEST] Stylizable progressbar (shadow-root) via User.css

### ISSUE THREAD

**Issue by hightechpresha** [rgthree/rgthree-comfy#239]
Hi guys, 

I am currently creating a theme (color palette) for Comfyui using the user.css from the web directory. With the progress bar (rgthree-progress-bar) I just can't get the div element (div.bar) in the shadow-root to grab. 

Can you design this if you have a lot of time so that you can style it yourself via user.css?

![rgthree-progress-bar](https://github.com/rgthree/rgthree-comfy/assets/20563696/a0c1b623-7600-42e2-9241-a2b1e082d7b8)

**Comment by rgthree** [comment]
Sure. There are now the following color CSS vars you can use for theming:

```css
--rgthree-progress-bg-color: rgba(23, 23, 23, 0.9);
--rgthree-progress-nodes-bg-color: rgb(0, 128, 0);
--rgthree-progress-steps-bg-color: rgb(0, 128, 0);
--rgthree-progress-error-bg-color: rgb(128, 0, 0);
--rgthree-progress-text-color: #fff;
```
