### ISSUE TITLE
Feature request: Context Big passing checkpoint name

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#24]
Just like Context Big now passes sampler and scheduler name, it would be great if it could pass the checkpoint name, too, and separately from the model value. So I could address this unfortunate situation:

<img width="1443" alt="Screenshot 2023-09-16 at 23 10 47" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/0694bfee-c4c3-4b97-942d-e8d7da053b53">

In reality, that checkpoint name doesn't have to be transported any further than the Loader node right there, but, for the sake of having a separate control panel, it would be extremely useful. 

Thank you

**Comment by alessandroperilli** [comment]
For more context about this request, I'm trying to get rid of many flying wires in the new 4.0 workflow:

<img width="1613" alt="Screenshot 2023-09-26 at 10 56 03" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/fbcab6fc-08e9-43d2-8c34-0db81a5e5c8b">

If the `Big Context` node could transport the model name (this request) in a way that is also compatible with the `Save Image w/ Metadata` node (#29), it would be fantastic.

The JSON is [here](https://drive.google.com/file/d/1PlMQ9npMW1s8W-iZt70-iuVW45OoI-UC/view?usp=sharing).

**Comment by rgthree** [comment]
I don't use the Efficiency nodes so I never needed to pass ckpt_name around, but I see no reason we can't. I've added it, though, see the comment in #29 as there's some considerations.
