### ISSUE TITLE
Make dependees of muted node not crash, but simply be ignored

### ISSUE THREAD

**Issue by zopieux** [rgthree/rgthree-comfy#241]
Hi,

Suppose a workflow:

```
[ random node X ]
        ↓
      [ rgthree Image Comparer ]
        ↑
[ random node Y ]
```

This works just fine. Now, if X or Y is muted (Ctrl-M), rgthree's Image Comparer (I suppose this applies to other nodes as well) will throw a nasty fatal error and abort processing. This is very annoying and gets in the way. This is contrary to most built-in Comfy nodes which simply display a red circle on the missing input, and silently prevents the rest of the dependencies of that muted input from running, which is exactly what I want when I mute a node: kill all the downstream branch, without crashing.

I'm not knowledgeable about Comfy node API, but I'm going to assume that if Comfy can do it correctly, it's probably possible to replicate this behavior as a custom node. I guess it's something about making the inputs not strictly required, or handling the failure gracefully?

Thanks.

**Comment by rgthree** [comment]
[c8603bc](https://github.com/rgthree/rgthree-comfy/commit/c8603bc24adb81a06c8132331c974d1e0266b6b3) Fixes this, thanks!
