### ISSUE TITLE
Is there an external one-click switch to control the fast group mute?

### ISSUE THREAD

**Issue by davidchenhs** [rgthree/rgthree-comfy#244]
After researching for a long time, I found that there is no such node
Is it possible to develop an external one-button function to control multiple groups of buttons in the fast group muter to turn on and off at the same time?
![QQ截图20240603114846](https://github.com/rgthree/rgthree-comfy/assets/164337292/4289bebf-1cd2-4736-9134-1fdfae76bac6)
One click to control the group nodes shown in fast group mute.
Because sometimes multiple groups fulfill a function.
But when you don't need the function, you need to close  relevant group node one by one, which is not an efficient way.

**Comment by rgthree** [comment]
You can connect the optional output to a Fast Action Button and have that button trigger a Mute/Bypass/Enable All.

**Comment by davidchenhs** [comment]
OMG! I got it! Thanks for creating it, I love this node!
