### ISSUE TITLE
[BUG] Power Lora Loader Strength value numeric entry popup doesn't work after sliding the value

### ISSUE THREAD

**Issue by tajino** [rgthree/rgthree-comfy#245]
Power Lora Loader Strength value numeric entry popup doesn't work after sliding the value. Clicking on the Strength numeric value after a newly added Lora slot correctly brings up the numeric entry popup, however after clicking and dragging to slide the value, clicking the value again no longer able to bring up the numeric entry popup.

Steps to reproduce the issue :
1. add Power Lora Loader node, add a Lora to the list.
2. click on the Strength value, a numeric entry popup will appear, working as expected.
3. now click drag on the Strength value to slide and change the value.
4. click the Strength value again, it doesn't bring up the numeric entry popup anymore.

A temporarily solution to this UI bug is to reload the browser.

Hope you can look into it. Thanks!

**Comment by tajino** [comment]
Thanks for fixing it. I have just tested it, the click for numeric entry popup now works, but click drag to slide the values no longer work.

**Comment by rgthree** [comment]
Ah, there was an issue introduced where dragging was only changing the second value (and if there was only one, not changing either). I've restored and fixed this. Should be fixed and restored.
