### ISSUE TITLE
Why does the cache seem to be useless?

### ISSUE THREAD

**Issue by davidchenhs** [rgthree/rgthree-comfy#248]
![image](https://github.com/rgthree/rgthree-comfy/assets/164337292/5ca8d2c8-80c1-479f-901c-c9a7724a4e1d)
There is no way to use the cache. It loads queue every time I click it. I don’t know what’s going on.

**Comment by rgthree** [comment]
I'm not sure what you're asking. That screenshot looks like you're just executing the same workflow over and over without any changes. ComfyUI won't do any work if there's nothing new to do.

If by "cache" you mean the optimization; all the optimization does is reduce the number of iterations ComfyUI normally does when recursively evaluating a workflow. Nothing more fancy.

**Comment by davidchenhs** [comment]
![image](https://github.com/rgthree/rgthree-comfy/assets/164337292/e0435fc1-aa48-40b9-8bea-c6761277a97f)
I only connected these two nodes, and then clicked on the queue. The queue could be loaded every time. It would have been cached before and would not continue to load. As a result, I could not use the automatic execution function.

**Comment by rgthree** [comment]
I see you've opened https://github.com/comfyanonymous/ComfyUI/issues/3686 which is likely more appropriate than in rgthree-comfy. Going to close this, but may add some details there :)
