### ISSUE TITLE
More inputs for context switches?

### ISSUE THREAD

**Issue by UnclePsymon** [rgthree/rgthree-comfy#253]
Hi there! I love your context nodes. I only wish there would be more possible inputs for the context switches. 5 are not enough for me ^^. Is that already possible, or maybe a good idea for the future?

**Comment by rgthree** [comment]
Makes sense to me. Added infinite `ctx_xx` inputs to Context Switch, Context Merge, and their Context Big versions. Each time you add a context input at the last position (after 5), a new empty one should appear after it.
