### ISSUE TITLE
Any Switch handling of empty text values

### ISSUE THREAD

**Issue by gshawn3** [rgthree/rgthree-comfy#254]
First, thank you for this amazing set of nodes. I'm not exaggerating when I say that the Any Switch is the backbone of my most powerful workflows. It's deceptively simple and intuitive, but it makes creating complex workflows feel like a breeze -- even more so when combined with nodes such as [Anything Everywhere](https://github.com/chrisgoringe/cg-use-everywhere).

I noticed that the Any Switch currently considers empty strings to be non-empty values:

![image](https://github.com/rgthree/rgthree-comfy/assets/133769806/85ae78c3-a1ce-4dc2-9810-c00071292f19)

In this simple workflow, I would expect "pineapple" to be displayed, since it's the first non-empty value.

The current behavior seems to run counter to the spirit of the node. It's easy enough to change (by adding a custom comparator for strings [here](https://github.com/rgthree/rgthree-comfy/blob/45781c3dbbe921847992084acc196d09d664901a/py/any_switch.py#L8)), but I wonder if that was an oversight, or if it was by design?

**Comment by gshawn3** [comment]
Oh, I also meant to mention: With the recent commit https://github.com/rgthree/rgthree-comfy/commit/45781c3dbbe921847992084acc196d09d664901a, Context Switch nodes now support a dynamic number of inputs. That's a nice upgrade!

This would also be a very useful feature for the Any Switch node. I think that's the only way the current node can still be improved, if it started with just two inputs and then added/removed inputs dynamically as needed.

**Comment by rgthree** [comment]
Hmmm. I'm honestly a little conflicted. The Any Switch was _really_ built to be used with _muting_. So, if you didn't want an empty string to be chosen, you would mute that node.

It is true that I added support for an empty Context being skipped if passed in (at least for the Context Switch, not sure if it works that way for the Any Switch if using Contexts). But I worry a bit about changing the behavior here, especially now that it's been out for so long...

While empty string may seem to make sense, I could see someone who uses an empty string as the last value so it always passes a valid string if others a muted. I could also think this opens the question up to empty lists being ignored, or a 0 number, etc.

For now, I think I'm erring on the side of not changing the existing behavior and having it rely on muting as the primary switching.

**Comment by rgthree** [comment]
Separately, dynamic inputs for the any switch should be easy. Good idea

**Comment by rgthree** [comment]
8c92a8a5d8352156b671f1c684b5d51a0b9f646a adds support for dynamic number of inputs to Any Switch!

**Comment by gshawn3** [comment]
> Hmmm. I'm honestly a little conflicted. The Any Switch was _really_ built to be used with _muting_. So, if you didn't want an empty string to be chosen, you would mute that node.
> 
> It is true that I added support for an empty Context being skipped if passed in (at least for the Context Switch, not sure if it works that way for the Any Switch if using Contexts). But I worry a bit about changing the behavior here, especially now that it's been out for so long...
> 
> While empty string may seem to make sense, I could see someone who uses an empty string as the last value so it always passes a valid string if others a muted. I could also think this opens the question up to empty lists being ignored, or a 0 number, etc.
> 
> For now, I think I'm erring on the side of not changing the existing behavior and having it rely on muting as the primary switching.

That makes sense and it's probably what I would do as well, considering the node has been out for a while and this change would break backwards compatibility.

Thank you for implementing dynamic number of inputs!

**Comment by gshawn3** [comment]
I think this is worth documenting here, in case it's useful to someone in the future:

With the dynamic number of inputs feature, the Any Switch node now prunes its inputs whenever any connections are changed. When determining whether an input should be pruned, the node checks if that input has a link: https://github.com/rgthree/rgthree-comfy/blob/8c92a8a5d8352156b671f1c684b5d51a0b9f646a/src_web/comfyui/utils_inputs_outputs.ts#L6

If like me, you use the Any Switch extensively with "virtual" links such as those created by Anything Everywhere, that will cause those inputs to be dropped. You'll need to add an extra condition or two at the line above.
