### ISSUE TITLE
Image Comparer in real time?

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#260]
I'm going to ask the impossible, so it's not even a feature request. 

Is it possible for the Image Comparer node to work without depending on the queue? In other words, could it display the images as soon as I connect/modify two Load/Get nodes instead of having to run through the queue?

**Comment by rgthree** [comment]
You should be able to right-click the comparer node and, assuming nothing else has changed (like a random seed, etc), Choose `Queue Selected Output Nodes (rgthree)` and the graph should only run the path for that node which should instantly load those image into the comparer (again, if nothing else has changed)

**Comment by alessandroperilli** [comment]
Yes, thank you. I'm trying to reduce friction so having to set the seed to fixed and press queue are the two things I was hoping to avoid. 

The fact is that this node is so incredibly useful that I wish it would just work all the time. 

BTW, and unrelated to this (so, sorry for the tangent), another incredibly useful feature for this node would be the capability to compare the just-generated image with the previously-generated image. I find myself wanting this 70 times a day.

To achieve that today, I have to generate an image, then load it with a LoadImage node, then generate another and let the Comparer do its job. 

All examples of friction I am hoping to avoid.

**Comment by rgthree** [comment]
> another incredibly useful feature for this node would be the capability to compare the just-generated image with the previously-generated image. I find myself wanting this 70 times a day.

If you have the Impact Pack with the `Image Sender` and `Image Receiver` nodes, then you can send the completed node to the image receiver, then pull that into the image compare. The next run, that previous received image should be sent to the compare, along with the new image.

Something like this:
![workflow](https://github.com/rgthree/rgthree-comfy/assets/476360/f7ff122e-ea27-457a-9e2f-8713287cd694)

**Comment by alessandroperilli** [comment]
I thought that both would change with the new seed. Very helpful, thank you.
