### ISSUE TITLE
Change progress bar position, to match the new Comfy UI menu bar.

### ISSUE THREAD

**Issue by JorgeR81** [rgthree/rgthree-comfy#261]
The Progress Bar (rgthree) is in front for the new Comfy UI menu bar.

https://github.com/comfyanonymous/ComfyUI/pull/3112

![bar](https://github.com/rgthree/rgthree-comfy/assets/72734038/71a0b1f0-928a-492b-b310-48c0b0c0e4a3)

![bar2](https://github.com/rgthree/rgthree-comfy/assets/72734038/5c295f71-bdf1-4a5a-9c95-c61a41cd3123)

**Comment by JorgeR81** [comment]
The Comfy UI menu bar also incorporates a progress bar, but it's a simplified version ( for the whole workflow ).

In the long term, a better solution could be to add an option to show a more complex bar in the Comfy UI menu itself.
( I don't know if there are plans for that )

![bar1](https://github.com/rgthree/rgthree-comfy/assets/72734038/c89c602e-0e23-4e9a-b12f-054f93a4ba41)

**Comment by DrJKL** [comment]
With the new menu bar's model (Canvas not being the entirety of the viewport), there are a lot of possibilities :-D

**Comment by JorgeR81** [comment]
Yes, we could have a sidebar instead, or a second, customizable bar, next to the menu bar.

We could have an option to pin down node widgets to the bar ( eg. the text prompt fields ).
And this setting could be stored in the workflow itself, so each one could have its own configuration.

I think this could replace the need for Comfy UI to have a "Frontend" !

**Comment by JorgeR81** [comment]
Ok, this is working, but there is no need for 3 bars ...

Can you add an option to draw only the current node bar. 
( But, you can keep the global completion % text for the workflow )

![bar3](https://github.com/rgthree/rgthree-comfy/assets/72734038/b65d0381-897d-4f07-a670-62be2e411d2c)
