### ISSUE TITLE
Fast Group Muter / Bypasser breaks when workflow contains a group with no color

### ISSUE THREAD

**Issue by gshawn3** [rgthree/rgthree-comfy#266]
I'm not sure exactly when this broke, but here are detailed repro steps:

1. Load an existing workflow that uses Fast Groups Muter / Bypasser nodes.
2. Edit any group in the workflow and set its color to "No color." (Right click on the group header, Edit Group, Color >, No color.)
3. For the sake of clarity, you can refresh the page and you'll notice that all the Fast Muter / Bypasser nodes are showing empty:

![image](https://github.com/rgthree/rgthree-comfy/assets/133769806/426c4ef5-113e-4f27-b96d-00fd9f419682)

4. Open the Properties Panel and verify the group selectors for these Fast Muter / Bypasser nodes are still correct.
5. Open up the JS console, where you'll see the following error:

![image](https://github.com/rgthree/rgthree-comfy/assets/133769806/877ca73c-277e-4a26-9c33-762ce531f298)
```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at FastGroupsMuter.refreshWidgets (fast_groups_muter.js:109:46)
    at FastGroupsService.run (fast_groups_service.js:39:18)
    at fast_groups_service.js:51:78
```

(`undefined` here is referring to `group.color`)

Hope this helps, thanks again for the awesome nodes!

**Comment by rgthree** [comment]
I couldn't reproduce this (when i select "no color" it just turns mine pink) but I made a fix for at least the error you shared, so you should be good.
