### ISSUE TITLE
Having both rgthree-comfy and ComfyUI-AnimateDiff-Evolved installed makes the majority of rgthree nodes disappear from add nodes/search nodes menu

### ISSUE THREAD

**Issue by AconexOfficial** [rgthree/rgthree-comfy#269]
Hi,
idk where to put it, so I do here, since it affects those nodes.
When having both rgthree-comfy and ComfyUI-AnimateDiff-Evolved installed most rgthree nodes disappear from the add nodes/search nodes menu. Already placed nodes inside of workflows still work though.
Tested with other custom nodes aswell as only having those two custom nodes installed.

Node menu without ComfyUI-AnimateDiff-Evolved installed
![Screenshot 2024-07-02 202950](https://github.com/rgthree/rgthree-comfy/assets/66433136/0116a43e-d11b-4828-9872-593572c85f04)

Node menu with ComfyUI-AnimateDiff-Evolved installed
![Screenshot 2024-07-02 202857](https://github.com/rgthree/rgthree-comfy/assets/66433136/6ddae4db-6c2f-4c3a-9bf6-2eba5aad89f5)

Idk if its an issue hailing from this or from the other repo, but just wanted to let you know, that this currently happens.

**Comment by judithdrive** [comment]
Same here. Fortunately, disabling `ComfyUI-AnimateDiff-Evolved` brings visibility back to the apparently missing `rgthree` nodes. For me a good temporary fix, because I'm currently not working on any animation; but I intend to get back to those projects.

**Comment by burning0xb** [comment]
the same issue, please help me. I need `ComfyUI-AnimateDiff-Evolved`

**Comment by rgthree** [comment]
Weird. I have AnimatedDiff installed and ever thing seems to be in order. I didn't update everything, maybe I'll try that. For now, I just added all the rgthree-comfy nodes to its own node selector in the "rgthree-comfy" menu item on right-click.

I don't think that will fix the node search if that's broken, but at least it's something for now.

**Comment by burning0xb** [comment]
> Weird. I have AnimatedDiff installed and ever thing seems to be in order. I didn't update everything, maybe I'll try that. For now, I just added all the rgthree-comfy nodes to its own node selector in the "rgthree-comfy" menu item on right-click.
> 
> I don't think that will fix the node search if that's broken, but at least it's something for now.

<img width="1364" alt="image" src="https://github.com/rgthree/rgthree-comfy/assets/17464897/f7cf6f93-9eaa-4ca2-b843-af4d5aca6287">
**I disable this , it works well.but when enable it,  missing some nodes**
<img width="885" alt="image" src="https://github.com/rgthree/rgthree-comfy/assets/17464897/2254c73a-d21b-442d-adf8-e012d5f5e4f5">

**Comment by burning0xb** [comment]
> Weird. I have AnimatedDiff installed and ever thing seems to be in order. I didn't update everything, maybe I'll try that. For now, I just added all the rgthree-comfy nodes to its own node selector in the "rgthree-comfy" menu item on right-click.
> 
> I don't think that will fix the node search if that's broken, but at least it's something for now.



<img width="1364" alt="image" src="https://github.com/rgthree/rgthree-comfy/assets/17464897/f7cf6f93-9eaa-4ca2-b843-af4d5aca6287">

**I disable this , it works well.but when enable it,  missing some nodes**

<img width="885" alt="image" src="https://github.com/rgthree/rgthree-comfy/assets/17464897/2254c73a-d21b-442d-adf8-e012d5f5e4f5">

**Comment by rgthree** [comment]
Yea, updating broke. Looks like it's from https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/commit/275e95147fb7902d9ef17770dba8878d857081b6 which breaks. Not sure how or why they broke other nodes yet.

**Comment by rgthree** [comment]
Hmm.. looks like AnimatedDiff broke other nodes too. For instance, the ComfyUI "Note" node also doesn't show up. I'll file a bug over there.

**Comment by rgthree** [comment]
If you want to fix it, you'll have to pull down an older commit of AnimatedDiff. You can do that in git manually by using `git reset --hard 05fa0698147ec35ef77c8c730aa4abe013c62fe5` which is the hash for the last commit at that repo that didn't break other nodes.

I can try to hack a fix around that breakage for rgthree-comfy, but I have no idea what other nodes outside of rgthree-comfy might be broken (like the default Note and Reroute nodes, etc.)

**Comment by burning0xb** [comment]
> If you want to fix it, you'll have to pull down an older commit of AnimateDiff. You can do that in git manually by using `git reset --hard 05fa0698147ec35ef77c8c730aa4abe013c62fe5` which is the hash for the last commit at that repo that didn't break other nodes.
> 
> I can try to hack a fix around that breakage for rgthree-comfy, but I have no idea what other nodes outside of rgthree-comfy might be broken (like the default Note and Reroute nodes, etc.)
> 
> EDIT: Actually... I changed my mind. I don't want to hack a fix since the AnimateDiff commit breaks other nodes too and I don't want to keep a hack in rgthree-comfy that affects the global node filtering. You can still get to rgthree-comfy nodes from the special menu item until it's fixed from AnimateDiff:
> 
> ![Screenshot 2024-07-03 002458](https://private-user-images.githubusercontent.com/476360/345280576-d6c73955-b5be-416a-ae60-615bb7af2f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTQ0MjcsIm5iZiI6MTcxOTk5NDEyNywicGF0aCI6Ii80NzYzNjAvMzQ1MjgwNTc2LWQ2YzczOTU1LWI1YmUtNDE2YS1hZTYwLTYxNWJiN2FmMmY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwODA4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTU2MzU1OTJkYmM1ZjBlZGVhOWFmNGZlN2U2MjUxOTcyZGU4ZjZkNDY4Y2VjMTA0NDcyNTI0MTA2ZDNmYWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c-Ol6I0QV8gZ3GESxWlvS6Ago3KzwNbP_u0F2EXAlJs)

Ok  I think you are right, I wiil try it. thanks a lot!

**Comment by rgthree** [comment]
Just for a paper trail, but the AnimateDiff project fixed the issue on their end pretty quickly.
