### ISSUE TITLE
我找不到image comparer 节点了，另外一台电脑可以有，重装这个插件也不行，问题出在哪呢？和其他的插件冲突？

### ISSUE THREAD

**Issue by wwb1988217** [rgthree/rgthree-comfy#270]

**Comment by wwb1988217** [comment]
![image](https://github.com/rgthree/rgthree-comfy/assets/25001544/25c74e82-d2e9-4bde-9823-b6f0c1095516)

**Comment by rgthree** [comment]
There was a bug in a separate custom extension that broke rgthree-comfynodes (and a bunch of others) from showing up here.

I assume you're using Kosinkadink/ComfyUI-AnimateDiff-Evolved which is what caused the issue. If you update that node, you should see rgthree-comfy nodes back.
