### ISSUE TITLE
After the recent comfyui update，somthing about api run the wrong way. 

### ISSUE THREAD

**Issue by kerker93** [rgthree/rgthree-comfy#273]
After the recent comfyui update, the realtime api in my photoshop  becomes extremely slow. I found that the process of transferring the image changes in Photoshop to comfyui is extremely slow. So I rolled back the comfyui version, the speed was normal again, and I saw  ”Using rgthree's optimized recursive execution“ now. I don't know if this is of reference value , but it definitely affects the daily work of users like me.

**Comment by rgthree** [comment]
The optimization has been there for about a year, and I don't see ComfyUI updating the execution at all that would cause this to break. Regardless, if you think it's negatively affecting your speed, you can turn off the optimization in the configuration (easiest is from the rgthree-comfy settings in the ComfyUI interface); turning it off from the UI will also turn it off in the backend (say, if using just an API).

Assuming that doesn't actually fix you speed, it seems your issue may either be ComfyUI itself, or another extension.
