### ISSUE TITLE
BUG: JavaSript seems to be causing issues with fonts/layout

### ISSUE THREAD

**Issue by gonzalu** [rgthree/rgthree-comfy#274]
Hi, just started to notice this problem with the latest update... Definitely gets fixed when I uninstall the custom node suite

![image](https://github.com/rgthree/rgthree-comfy/assets/32348862/833300cf-a792-4af1-8dde-0267704e11ae)

and here it is with the custom node removed

![image](https://github.com/rgthree/rgthree-comfy/assets/32348862/c1094d9c-a34a-4e87-b158-306c83b34764)

Removing the nodes from the workflow does not resolve the issue. It worked fine earlier today. 

Cheers and thank you for an awesome set of nodes.

**Comment by gonzalu** [comment]
Here is a short screen grab to show how it is behaving. 


https://github.com/rgthree/rgthree-comfy/assets/32348862/cc1fa7fe-3565-4ac4-83e1-63dacdb769fd

**Comment by gonzalu** [comment]
UPDATE: 

The problem goes away when you enable the new BETA ComfyUI Menu Bar ... 

Disabling this new feature and going back to the floating Toolbar does not re-introduce the issue. Looks like the way to fix it is to at least enable the new menu bar once. Will keep an eye on it. 

Thank you.

**Comment by gonzalu** [comment]
Nah, spoke too soon... it is back :( I am using the side bar floating toolbar and the text/layout is once again distorted.

**Comment by alessandroperilli** [comment]
Same here. And I fixed it by enabling the new BETA ComfyUI Menu Bar.

**Comment by rgthree** [comment]
I actually can't see the textbox's offset like this, but I think I know what the issue is, similar to #275. A fix just now should have fixed it. LMY if it's still present after the latest.
