### ISSUE TITLE
BUG: Prompt Progress Bar stuck at top of window

### ISSUE THREAD

**Issue by unsivilaudio** [rgthree/rgthree-comfy#275]
New bug introduced.  **_IF you do not use the new menu bar layout._**  The progress bar is stuck at the top of the screen (regardless of setting).  However if you enable the new menu bar (top or bottom, it does not matter), the progress bar position will be respected.

**Comment by JorgeR81** [comment]
I also noticed a bug, but in my case it's different. 
For me, the progress bar is only visible, if the new menu is enabled. 
If the old menu is used, the progress bar is not visible. 
This happens whether the progress bar is set to be on top or at the bottom for the screen. 
I'm on Windows 10, using Google Chrome.

**Comment by Ainaemaet** [comment]
Same issue as both the preceding posts. Didn't seem to start happening until recently after trying ComfyUI new beta UI and then going back to the old one. Now I deal both with the progress bar being stuck at the top like and not being able to switch it to the bottom like @unsivilaudio OR it just disappears like @JorgeR81

**Comment by rgthree** [comment]
Ah, interesting. ComfyUI added new markup for their own top/bottom bar, which the progress bar is now using. But I guess then it takes away the necessary CSS if you're not using the bar. Latest push should have fixed it.
