### ISSUE TITLE
On July 10, 2024, after updating the plugin, the copy node, paste error occurred

### ISSUE THREAD

**Issue by shumoLR** [rgthree/rgthree-comfy#276]
![image](https://github.com/rgthree/rgthree-comfy/assets/169419160/77499abe-c33b-4dd7-afc5-6106696032ed)
On July 10, 2024, after updating the plugin, the copy node, paste error occurred. It is pasted to another node. What is the problem?

**Comment by rgthree** [comment]
Hmm. I have no idea why that is happening, seems to have something to do with the new layout system for the beta bar. I just made a change to be more backwards compatible with the old, non-beta, layout, which seems to have fixed this as well.
