### ISSUE TITLE
comfyui-workspace-manager and rgthree-comfy cannot be enabled at the same time

### ISSUE THREAD

**Issue by Rheron1848** [rgthree/rgthree-comfy#277]
https://github.com/11cafe/comfyui-workspace-manager
the link above is the extension mentioned above.

If both of them are enabled, comfyui webpage will not display any node, though the menu of comfyui can display and be used normally. clear flow or load default will not help, like this:
![image](https://github.com/rgthree/rgthree-comfy/assets/99803057/ba044588-7bc8-4e51-a94d-e7bfceea2517)
and when this occurs, no error reports in the terminal.
`| Comfy-Easy-Use v1.2.0: Loaded
comfyui-1  |
comfyui-1  | [rgthree] Loaded 40 exciting nodes.
comfyui-1  | [rgthree] Will use rgthree's optimized recursive execution.
comfyui-1  |
comfyui-1  | [Crystools INFO] Crystools version: 1.13.1
comfyui-1  | [Crystools INFO] CPU: Intel(R) Xeon(R) Platinum 8352V CPU @ 2.10GHz - Arch: x86_64 - OS: Linux 5.4.0-186-generic
comfyui-1  | [Crystools INFO] GPU/s:
comfyui-1  | [Crystools INFO] 0) NVIDIA GeForce RTX 4090
comfyui-1  | [Crystools INFO] 1) NVIDIA GeForce RTX 4090
comfyui-1  | [Crystools INFO] 2) NVIDIA GeForce RTX 4090
comfyui-1  | [Crystools INFO] NVIDIA Driver: 555.42.02
comfyui-1  | Workspace manager - Openning file hash dict
comfyui-1  | 🦄🦄Loading: Workspace Manager (V2.1.0)
comfyui-1  |
comfyui-1  | Import times for custom nodes:
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/websocket_image_save.py
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/rembg-comfyui-node
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/rembg-comfyui-node-better
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/comfyui-browser-main
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/cg-use-everywhere
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/ComfyUI-post-processing-nodes
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/masquerade-nodes-comfyui
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/batchImg-rembg-ComfyUI-nodes
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/sdxl_prompt_styler
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/comfy-image-saver
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/ComfyUI_experiments
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/comfyui-sixgod_prompt
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/ComfyUI_essentials
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet-main
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/comfyui-inpaint-nodes
comfyui-1  |    0.0 seconds: /app/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/comfyui-animatediff
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Studio
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/ComfyUI-KJNodes
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Manager
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/efficiency-nodes-comfyui
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/comfyui-workspace-manager
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/rgthree-comfy
comfyui-1  |    0.1 seconds: /app/ComfyUI/custom_nodes/ComfyUI-BiRefNet-ZHO
comfyui-1  |    0.2 seconds: /app/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
comfyui-1  |    0.2 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
comfyui-1  |    0.3 seconds: /app/ComfyUI/custom_nodes/comfyui_controlnet_aux
comfyui-1  |    0.4 seconds: /app/ComfyUI/custom_nodes/comfyui_segment_anything
comfyui-1  |    0.4 seconds: /app/ComfyUI/custom_nodes/ComfyUI_FizzNodes
comfyui-1  |    0.5 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Easy-Use
comfyui-1  |    0.5 seconds: /app/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
comfyui-1  |    0.7 seconds: /app/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
comfyui-1  |    0.7 seconds: /app/ComfyUI/custom_nodes/ComfyUI_LayerStyle
comfyui-1  |    0.7 seconds: /app/ComfyUI/custom_nodes/DZ-FaceDetailer
comfyui-1  |    1.8 seconds: /app/ComfyUI/custom_nodes/was-node-suite-comfyui
comfyui-1  |    2.3 seconds: /app/ComfyUI/custom_nodes/comfyui-mixlab-nodes
comfyui-1  |    2.6 seconds: /app/ComfyUI/custom_nodes/ComfyUI-YoloWorld-EfficientSAM
comfyui-1  |    2.8 seconds: /app/ComfyUI/custom_nodes/ComfyUI-Crystools
comfyui-1  |   12.0 seconds: /app/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet
comfyui-1  |
comfyui-1  | https_key OK:  /app/ComfyUI/custom_nodes/comfyui-mixlab-nodes/https/certificate.crt /app/ComfyUI/custom_nodes/comfyui-mixlab-nodes/https/private.key
comfyui-1  |
comfyui-1  |
comfyui-1  |
comfyui-1  |
comfyui-1  | Starting server
comfyui-1  | To see the GUI go to: http://127.0.0.1:8188
comfyui-1  | To see the GUI go to: https://127.0.0.1:8189
comfyui-1  | FETCH DATA from: /app/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]`

and when i disable the comfyui-workspace-manager, everthing is back to normal. 
![image](https://github.com/rgthree/rgthree-comfy/assets/99803057/aea2bcec-765c-41d5-9d7b-712a994d7f9b)

so i guess it is a conflict between this two extensions.

**Comment by laitianwen** [comment]
I also have this problem,

**Comment by JorgeR81** [comment]
Try disabling the comfyui-workspace-manager,
or enabling the new [ Beta ] Comfy UI menu in the settings.
 
The new Comfy UI menu was interfering with this comfyui-workspace-manager,
https://github.com/comfyanonymous/ComfyUI/pull/3112#issuecomment-2189566330
although it should be fixed now. 
https://github.com/comfyanonymous/ComfyUI/pull/3112#issuecomment-2190790884

Now that rgthree progress bar was updated to be compatible with the new Comfy UI menu, it may be interfering with the comfyui-workspace-manager
[#275](https://github.com/rgthree/rgthree-comfy/issues/275)

**Comment by rgthree** [comment]
I can't seem to reproduce this exactly even with workspace manager, but I just made a change to be more backwards compatible with the old, non-beta, layout. Can someone who is experiencing this pull the latest and try?

**Comment by laitianwen** [comment]
It turned out to be a problem with the [Beta] Comfy UI menu. I deleted the comfyui-workspace-manager and rgthree, but the workflow also failed to load.

**Comment by JorgeR81** [comment]
@laitianwen, In that case it may be a conflict between the new menu and another extension.

This user disabled all extensions, one by one, and found issues with [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack), and [ComfyUI-N-Sidebar](https://github.com/Nuked88/ComfyUI-N-Sidebar).
https://github.com/comfyanonymous/ComfyUI/issues/3894

But for other users here, these extensions are working fine with the new menu. 
https://github.com/rgthree/rgthree-comfy/issues/278#issuecomment-2220378506

It could be weird interaction between multiple extensions, and the new menu ...

**Comment by laitianwen** [comment]
Indeed, I disabled ComfyUI-N-Sidebar and now the beta menu and rgthree run fine at the same time
