### ISSUE TITLE
After the update, there's something on top blocking me.

### ISSUE THREAD

**Issue by 807502278** [rgthree/rgthree-comfy#278]
I'm sure it's the problem of rgthree, because it's okay after I delete it. 
![1720603907641](https://github.com/rgthree/rgthree-comfy/assets/46019416/4966229e-bb3d-439e-9d1d-db77328e1af0)

I tried to adjust it in the settings but to no avail, for example, I canceled the progress bar, but this thing is still here.
![S3WEX{ UT1~`P}ZFJ33N~(6](https://github.com/rgthree/rgthree-comfy/assets/46019416/4e67f7e3-8c62-45ba-a116-60fe3b68f6e5)

**Comment by JorgeR81** [comment]
Try disabling the ComfyUI-N-Sidebar
The new Comfy UI menu is interfering with ComfyUI-N-Sidebar
https://github.com/Nuked88/ComfyUI-N-Sidebar/issues/79

Now that rgthree progress bar was updated to be compatible with the new Comfy UI menu, it's probably also interfering with the ComfyUI-N-Sidebar too.
https://github.com/rgthree/rgthree-comfy/issues/275

**Comment by rgthree** [comment]
I can't seem to reproduce this exactly even with workspace manager, but I just made a change to be more backwards compatible with the old, non-beta, layout. Can someone who is experiencing this pull the latest and try?

**Comment by 807502278** [comment]
> Try disabling the ComfyUI-N-Sidebar, or enabling the new [ Beta ] Comfy UI menu in the settings.
> 
> The new Comfy UI menu is interfering with ComfyUI-N-Sidebar, but it may also be due to some interactions with other extensions ( e.g. 3D-Pack ) [Nuked88/ComfyUI-N-Sidebar#79](https://github.com/Nuked88/ComfyUI-N-Sidebar/issues/79)
> 
> Now that rgthree progress bar was updated to be compatible with the new Comfy UI menu, it's probably also interfering with the ComfyUI-N-Sidebar too. #275

Currently I haven't encountered any conflict situations between N-Sidebar or 3dpack and the new menu of ComfyUI. What I have a conflict with is Crystools and rgthree-comfy. To be exact, there is no conflict with Crystools, but its stacked UI makes the new menu very high.
![image](https://github.com/rgthree/rgthree-comfy/assets/46019416/d23550e8-76a7-4454-827a-b8338ec2483d)

**Comment by 807502278** [comment]
> I can't seem to reproduce this exactly even with workspace manager, but I just made a change to be more backwards compatible with the old, non-beta, layout. Can someone who is experiencing this pull the latest and try?

Thank you very much. I just updated and the issue has been fixed : )
