### ISSUE TITLE
Copy/paste of nodes stopped working.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [rgthree/rgthree-comfy#279]
It has taken me a while to track it down, but it's the rgthree nodes that are causing the problem.
Until today I was able to select nodes(s), copy them (ctrl+c) and paste them (ctrl+v) in the same workflow, and even to another tab. I used it yesterday without any problem, I update every day, including this morning. Now, if I try to copy/paste, I can only paste the last node I copied yesterday, even if I right click a node and copy it to clipspace I get the same behaviour. I have tried in private browsing and another browser, but nothing is pasted. I can copy/paste text within nodes, but not the nodes themselves.

Originally opened at: https://github.com/comfyanonymous/ComfyUI/issues/3995

**Comment by GalaxyTimeMachine** [comment]
I've resolved this by deleting the rgthree custom node folder and then reinstalling it via the manager. There must be some lingering old code in there that caused it.

**Comment by drgrib** [comment]
I tried this. It didn't work.

**Comment by drgrib** [comment]
Maybe this is a new instance of the bug related to Chrome support.
https://www.reddit.com/r/comfyui/comments/1iixut0/cant_copy_nodes_anymore/
