### ISSUE TITLE
KSampler Config not compatible with SamplerCustom

### ISSUE THREAD

**Issue by Steudio** [rgthree/rgthree-comfy#285]
Is there a way to have the SAMPLER output of KSampler Config compatible with SamplerCustom ?
![image](https://github.com/user-attachments/assets/5ea3b8f9-70c2-45e5-b91f-4e0cb3ca3599)
Thanks

**Comment by JorgeR81** [comment]
You can use the [ KSamplerSelect ] node.

![node](https://github.com/user-attachments/assets/6c19adfa-a998-4e37-89a2-8533dd6b8cca)

**Comment by Steudio** [comment]
Perfect ! Thank you so much
