### ISSUE TITLE
Bookmarks now broken in two important ways

### ISSUE THREAD

**Issue by cor-of-org** [rgthree/rgthree-comfy#286]
The rgthree bookmarks used to be the most perfect, beautiful node in ComfyUI. Now they are a daily annoyance.

1. The title used to be a perfectly understandable icon. Now even old workflows which had this perfect icon now say "Bookmark (rgthree)". I had to hack the icon into the bookmarks code to prevent mental breakdown. PLEASE REVERT THIS MADNESS!

2. I used to be able to (do something) with my keyboard (or mouse) and then activate a bookmark immediately. For example, enter a value into an input, e.g..  0.5<enter>5, "5" being me activating my bookmark. No more.

Same if I click the queue button. I can no longer hit my numeric keypad straight after. Now I need to click on the canvas to activate a bookmark! 

A keyboard shortcut that needs me to use the mouse. Eh?

**Comment by rgthree** [comment]
Sometimes ComfyUI's changes break other nodes. These should now be addressed.

**Comment by cor-of-org** [comment]
Sadly this continues to haunt me. I load perfectly fine workflows from my AI history and it's all "Bookmark (rgthree)". It's just not bookmark-like in any way. It's like using a damp sweaty sock as a bookmark in your first edition copy of "THE WORLD I LIVE IN". I'm happy to appreciate your work, but not like this.

By way of tipping the chef or what-have-you; not wanting this relationship to be completely one-sided, here's an idea for a "Killer Feature" you could incorporate..

Understand, I think this simple bookmark node you have created is one of the most important nodes in ComfyUI. That's why I'm spending time typing here instead of some other life thing. I fucking love this node. I have a macro that will rename them instantly to ".", which at least suspends my heart palpitations until I can rename them to (oh f*ck! another killer idea!) _the number of the keypad they correspond to_. 

On to our main killer feature..

Instead of creating a bookmark under the cursor at 100%, etc.; why not (a modifier would be fine; in fact, perfect) create the bookmark _in position_; i.e. Right up there in the top-left where it belongs _at the exact zoom level I am now at_.

Holy $hit! That would save me so much time and effort!

You incorporate that and then you have 50,000 people (or whatever your userbase is, and always growing) all thanking you daily for saving them so much time and effort. Think of the love! What a STAR!

ps. Since a recent update, at some point hotkeys now cease to work. Switching to a different (ComfyUI) tab and back fixes it. Should I open a different issue for this?
