### ISSUE TITLE
Can Boolean button be converted to input, so that the triggering rules can be customized

### ISSUE THREAD

**Issue by davidchenhs** [rgthree/rgthree-comfy#287]
This node is great and needs to be used in almost every workflow. However, manual adjustment is still a bit troublesome in some cases. Can the Boolean button be converted into input, so that the triggered rules can be customized to achieve automatic switching instead of manual switch?

**Comment by davidchenhs** [comment]
for mute button and bypass button

**Comment by 52Hz-p** [comment]
是的，非常需要此功能，我查看了其他的组开关，都不能，不知道是否是对于组的开关无法控制，我查看了普通布尔节点和组开关他们的类型都是布尔，但是不知道为啥不可以转换成输入

**Comment by rgthree** [comment]
This comes up a lot but, unfortunately, it's not really possible to toggle mute/bypass with an input as they are in two completely different phases of execution.

Muting, Bypassing, and other actions are all modifying the active workflow in the browser in real-time. Whether you use ctl+M, or a Fast Muter, etc. when you do so, it's changing those nodes' status right there in the browser workflow--there's no communication with the server.

An input, however, is evaluated while the server is executing and, at that point it is infeasible to mute/bypass a node or group based on the value of that input mid-execution as we're no longer in the browser to manipulate the workflow that would have been sent to the server. (At least not without an extensive re-write to ComfyUI's execution and APIs.)

**Comment by DrJKL** [comment]
>  [At least not without an extensive re-write to ComfyUI's execution](https://github.com/comfyanonymous/ComfyUI/pull/2666)

**Comment by rgthree** [comment]
Yea, this is a promising change, but it’s still not gonna be enough.

The API format doesn’t know about “groups” nor even the position of the items in the workflow. I’m also unsure that the API version contains muted nodes at all.

What would need to happen is a rewrite that allows the server to go through the workflow data, calculate the position of the nodes and if they overlap with a group (all without the LiteGraph framework), and then mute the nodes that overlap, etc.

Not impossible, but it’s entirely new, complex work.

**Comment by davidchenhs** [comment]
Can we add inversion between repeater and relay?

**Comment by rgthree** [comment]
> Can we add inversion between repeater and relay?

Yes, it’s part of the Relay’s properties. You can see more in the docs https://github.com/rgthree/rgthree-comfy?tab=readme-ov-file#mute--bypass-relay
