### ISSUE TITLE
Error occurred when executing VHS_LoadVideoPath:  video is not a valid path: .\ComfyUI\Output\Projects\video\video.mp4

### ISSUE THREAD

**Issue by guushenaichitang** [rgthree/rgthree-comfy#289]
What kind of question is that
![微信截图_20240730130201](https://github.com/user-attachments/assets/fc6d4b72-241d-4af0-a664-3d0f0bd3ba41)
![微信截图_20240730131314](https://github.com/user-attachments/assets/02b8a1cb-ebf4-42a5-9214-5997d1fd5eea)

**Comment by rgthree** [comment]
What kind of question is what?

I don’t think this is an error in rgthree-comfy. You can try to disable the execution optimization in settings, but I’d bet you’ll still get this error.

You should create an issue for the VHS nodes and see if they can help you.
