### ISSUE TITLE
[Feature Request] Programmatic Fast Bypasser

### ISSUE THREAD

**Issue by gisu** [rgthree/rgthree-comfy#290]
Currently the Fast Bypasser works by manually activating the switches. My idea would be to add an additional input to the bypasser with the setting "always one" with which I pass an integer which then switches one of the switches?

In my case I have created a few nodes with which I change the setup of the sampler via a txt file, the name of the checkpoint is read out and then the respective setting parameters are automatically changed (https://github.com/gisu/comfyui-foxpack). Optionally I can enter whether it is an SD1.5 or SDXL checkpoint. As long as I work with regular switches, this works quite well because I can pass an integer into an input there. The only thing missing is the fast bypass, where I currently always have to do it manually.

**Comment by rgthree** [comment]
This comes up a lot but, unfortunately, it's not really possible to toggle mute/bypass with an input as they are in two completely different phases of execution.

Muting, Bypassing, and other actions are all modifying the active workflow in the browser in real-time. Whether you use ctl+M, or a Fast Muter, etc. when you do so, it's changing those nodes' status right there in the browser workflow--there's no communication with the server.

When you queue a prompt, ComfyUI takes the current browser workflow, and sends it _as-is_ to the backend, which executes it independently. Things that have been muted/bypassed are stuck as muted/bypassed (I actually think Comfy doesn't even send them to the backend).

Further, an input is a value passed from one node to a connecting node _in the backend, during that nodes' execution._ At this point, it is infeasible to then mute/bypass a node or group based on the value of an input as we're no longer in the browser to manipulate the workflow that would have been sent to the server. (At least not without an extensive re-write to ComfyUI's execution and APIs.)

**Comment by gisu** [comment]
Ok, thank you for the explanation. It will probably need lifecycle hooks and only the ComfyUI team can integrate them.
