### ISSUE TITLE
Seed node to noise

### ISSUE THREAD

**Issue by hexive** [rgthree/rgthree-comfy#298]
Is there a way to use your seed control node with noise inputs (eg SamplerCustomAdvanced)?

Thanks in advance!

**Comment by rgthree** [comment]
Sure. In the `RandomNoise` node you can right-click, and change the `noise_seed` widget to an input, then plug the rgthree-comfy seed node to it:

![Screenshot 2024-08-14 235659](https://github.com/user-attachments/assets/e7ca1049-b19a-4812-ab99-c9ca5dcaa14e)
