### ISSUE TITLE
bug when use eff Ksampler XL  and  eff Ksampler, 

### ISSUE THREAD

**Issue by xueqing0622** [rgthree/rgthree-comfy#30]
bug when use eff Ksampler XL  and  eff Ksampler, the second Ksampler will stop or very slow.

**Comment by rgthree** [comment]
What is "eff KSampler"; is that a different custom node? I'm not sure rgthree-comfy nodes would be the cause of Ksampler being slow.

**Comment by xueqing0622** [comment]
sorry, it is my mistake
