### ISSUE TITLE
Shift+R not work for create reroute with new comfyui frontend

### ISSUE THREAD

**Issue by bananasss00** [rgthree/rgthree-comfy#300]
title

**Comment by rgthree** [comment]
Thanks. Looks like the new UI is not firing the same when you start to drag a noodle (and so the reroute service isn't listening for key events)

**Comment by rgthree** [comment]
Okay, looks like the LiteGraph in the new UI has changed pretty significantly. I filed a bug at https://github.com/Comfy-Org/litegraph.js/issues/75 but I'm now a bit more worried there are more changes that have caused regressions.

**Comment by rgthree** [comment]
I fixed this forward for rgthree-comfy reroute nodes. Latest pull should get it working again.
