### ISSUE TITLE
BUG-Image comparison

### ISSUE THREAD

**Issue by anlin857** [rgthree/rgthree-comfy#302]
Image comparison cannot open right-click menu。

**Comment by rgthree** [comment]
I can't seem to reproduce this. The menu opens fine for me.

Can you open your Browser DevTools Console (usually F12) and check if there are any new errors that appear when you right-click in the comparison node?

**Comment by anlin857** [comment]
ComfyUI_NestedNodeBuilder    I checked if there is a conflict with this, just delete it
