### ISSUE TITLE
Update for new comfyui 

### ISSUE THREAD

**Issue by KintCark** [rgthree/rgthree-comfy#304]
Please update this for latest comfyui version I need encursive execution to speed up my generation I'm using flux BTW it take sd 20 minutes for a single image generation 😭

**Comment by rgthree** [comment]
I think there are a few, hopefully minor, UI issues that make the new UI somewhat incompatible. However, I think the new inverted execution model makes the execution speed as fast as the rgthree execution optimization, so I wasn't planning on address that with the new code.

**Comment by KintCark** [comment]
> I think there are a few, hopefully minor, UI issues that make the new UI somewhat incompatible. However, I think the new inverted execution model makes the execution speed as fast as the rgthree execution optimization, so I wasn't planning on address that with the new code.

Is the inverted execution a node or already come with comfyui?

**Comment by rgthree** [comment]
It's baked into the ComfyUI backend now, if you've updated ComfyUI then you already have it.
