### ISSUE TITLE
[BUG] New UI: `Workflow Bookmarks` menu expansion in wrong direction

### ISSUE THREAD

**Issue by sansmoraxz** [rgthree/rgthree-comfy#306]
When pinning the toolbar to bottom, the bookmark menu expansion is going in the wrong direction and hence out of screen.

![image](https://github.com/user-attachments/assets/74ebc8ea-5054-4955-a897-25aeec8d4e82)

**Comment by drmbt** [comment]
you've opted to put the menu on the bottom; it looks like bookmarks isn't smart enough to know your menu position preference. you can put the menu on the top and then it works fine

**Comment by sansmoraxz** [comment]
Yes, that's the bug.

**Comment by rgthree** [comment]
The bars are just using the new ComfyUI's built-in popup. I don't see a way to force it to pop up above the bar... but I notice the other menu's are. I'll have to see how they're doing it or file a bug with Comfy. Thanks for reporting

**Comment by rgthree** [comment]
Ok, this should now be fixed. Thanks for the report
