### ISSUE TITLE
missing badges

### ISSUE THREAD

**Issue by dryodryo** [rgthree/rgthree-comfy#309]
Hi,

"We don't need no stinking badges"

I am trying to grab the pixel resolution values from a node that generates them automatically, yaResolutionSelector. These width and height values are passed through workflow connections, and displayed as read-only info on the custom node itself, but are not exposed in any widget.

The purpose here is to add the resolution values to the filename via save_image_extended, which relies on widgets and badge numbers.

I thought I could use rgthree display_any or display_int to do this. But these nodes do not have badge numbers. This confuses me because I thought all nodes would have badge IDs.

So, why don't some of the rgthree nodes have badge IDs?

Any suggestions on how to display a connection as a widget?

Thanks

**Comment by drmbt** [comment]
I would posit a guess here that pure js nodes that don't actually serve any function in the api and only run visually in the webui aren't assigned an ID in the same was as normal nodes. I'd imagine the bypassers are the same. 

To achieve your desired goals, I'd maybe try something like Get Resolution node from Crystools, and convert those ints to strings to concatenate into your file name

**Comment by dryodryo** [comment]
Thanks, it turns out that the hard coded "resolution" key works fine in save_image_selected. Apparently it is finding the actual resolution and not grabbing it from some widget in the graph.

But I still wonder how to make an arbitrary connection value visible as a widget.

**Comment by rgthree** [comment]
This is actually because I original removed the title bar and I guess the Comfy Manager requires the title bar to be visible to show the badge.

I went ahead and added it back as I regret forcing it to be hidden; though we'll see if anyone notices/complains.

Badges should appear now with the latest.
