### ISSUE TITLE
[BUG] Queue selected broken on nodes with context menu items with title but no content

### ISSUE THREAD

**Issue by DrJKL** [rgthree/rgthree-comfy#310]
https://github.com/rgthree/rgthree-comfy/blame/17df78ec03aadc315dbac7f40761fae05d57ca9e/src_web/comfyui/menu_queue_node.ts#L63

Just needs a null safe access modifier:
![image](https://github.com/user-attachments/assets/53e2d869-939f-456b-a9d5-95c14af38e45)

**Comment by rgthree** [comment]
Ha, that was not typed in the LiteGraph spec as an optional field. Made it optional and patched up everywhere that would break if it's not available.
