### ISSUE TITLE
Default size reroute

### ISSUE THREAD

**Issue by alexbofa** [rgthree/rgthree-comfy#32]
Hello, Is it possible to choose a standard `reroute` size without changing the code?

https://github.com/rgthree/rgthree-comfy/assets/58225118/3f1d28d8-0389-4739-9e39-0b4e27e883ad

At 23 seconds, you can notice a problem with the `small reroute` that I encounter

**Comment by rgthree** [comment]
What I usually do is copy + paste an existing reroute node that has the size and direction (or alt+drag an existing one to clone it).

I could expose a default in settings I suppose, but not without code changes.

**Comment by alexbofa** [comment]
Yes, I've done that before too
From a [pythongosssss](https://github.com/pythongosssss/) has [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) a convenient function has appeared, choose reroute by default. I use yours, when you click on a point in the node with the middle mouse button, reroute appears, this is very convenient and quickly simplifies the work.

**Comment by rgthree** [comment]
Ah, that's cool!

Alright, added the ability to define some defaults in the config json file.

You can create a `rgthree_config.json` file at `comfyui/custom_nodes/rgthree-comfy/rgthree_config.json` (or, copy the `rgthree_config.json.default` file to `rgthree_config.json`) and you can define some defaults for reroute there. You'll need to restart ComfyUI for the config to load.

```json
{
  "nodes": {
    "reroute": {
      "default_width": 40,
      "default_height": 30,
      "default_resizable": false,
      "default_layout": ["Left", "Right"]
    }
  }
}
```

**Comment by alexbofa** [comment]
Thank you! It's awesome
