### ISSUE TITLE
[Feature Request] Fast toogle button for "Queue Group Output Nodes" 

### ISSUE THREAD

**Issue by ZorisBube** [rgthree/rgthree-comfy#320]
First off all I would like to thank you for these great nodes. 

I like and use the fast toggles on "group headers". I would like to know if it is possible to add a feature, a little toggle button like fast toggles in the headers for "Queue Group Output Nodes" ?  I know it is just a  right click away but it would be nice to have that. 

Best regards!

**Comment by DJBizzle** [comment]
This quality-of-life improvement would be amazing!
A button to queue up individual groups - even added an option to the fast actions button would be great.
Thanks for all your hard work, RG!

**Comment by rgthree** [comment]
Love it, makes sense to me. Added it as an option in the settings.

**Comment by ZorisBube** [comment]
Thank you rgthree!

**Comment by DJBizzle** [comment]
Amazing! Thank you
