### ISSUE TITLE
rgthree image compare are not working after ComfyUI updating

### ISSUE THREAD

**Issue by ultimatech-cn** [rgthree/rgthree-comfy#328]
As subject.
If I want to use it, I need to start a old version of comfyUI
Any plan to fix that?

**Comment by rgthree** [comment]
It's working for me on the latest ComfyUI. Perhaps there's a conflict with another extension you have. If you open the browser devtools (usually F12) you could see if there are applicable errors in the console.

A different bug mentioned that "ComfyUI-DeepFuze" broke other nodes, do you have that installed? If so, does it work if you remove it?

**Comment by ultimatech-cn** [comment]
Thanks a lot  for the reply. I am not familiar with frontend dev. When F12, got following 
![image](https://github.com/user-attachments/assets/a5048ad2-b61a-4764-89bb-248482c69a7e)

I will try to make a new comfyUI instance to check the conflict with other nodes.

**Comment by secretivebanana** [comment]
It seems that this issue relates to SaltAI custom node. See https://github.com/get-salt-AI/SaltAI/issues/20.

**Comment by DeepSeaCatz** [comment]
Lol I came here to figure out how I fixed this issue after updating all my nodes and here we are.
Yeah just rename the helpbutton.js files in `SaltAI/web/helpbutton.js` to `SaltAI/web/helpbutton.js.bak` and this fix this comparer node somehow

**Comment by Milor123** [comment]
> Lol I came here to figure out how I fixed this issue after updating all my nodes and here we are. Yeah just rename the helpbutton.js files in `SaltAI/web/helpbutton.js` to `SaltAI/web/helpbutton.js.bak` and this fix this comparer node somehow

I've Disable it and solve my slider, thank u very much guys !!
