### ISSUE TITLE
Consideration - Fast Actions Button - Is the 'action' button necessary?

### ISSUE THREAD

**Issue by Trobinou** [rgthree/rgthree-comfy#33]
Is this button really necessary to confirm the choices?
Indeed, I noticed that when the workflow loads, I have to start by pressing this button to validate the displayed choices. If I don't do that, the actions don't proceed as displayed.
Furthermore, I often forget (my fault) to confirm my choices because, for me, it is logical that when I see 'enable,' for example, the action should be triggered without the need to validate it.

So my question is: could we do without this button?

**Comment by rgthree** [comment]
Hmm.. there's only one actual "button" on the `Fast Actions Button` node and that's what actually runs the actions. Is that what you mean by "validate" ?

So, taking the following example, it has one button ("Action!" and three combos to select which actions to run).
![fast_actions_button](https://github.com/rgthree/rgthree-comfy/assets/476360/2155fa37-5753-40fd-9ab5-9f55195f40a8)
- Clicking that "Action!" button will run the three actions which, in this case, are:
  - Resetting the connected `Seed` node to randomize
  - Setting all toggles on the connected `Fast Muter` to "mute"
  - And then queuing the prompt to run

Perhaps I'm misunderstanding, but the button surely needs to exist to click it :)

**Comment by Trobinou** [comment]
The choice of the term 'validate' was not appropriate, but indeed, it is about clicking the 'Action!' button to execute the selected actions.
What I meant is, would it not be possible to choose the desired option, for example, for the 'seed' in your example, between 'Fixed-increment-decrement-randomize,' and have the choice executed without pressing the 'Action!' button?

**Comment by aegis72** [comment]
I think the intention of this node might be as a macro…ie, one button that sets the workflow in a specific state.
In my workflow AegisFlow, I’d connect a huge host of nodes that set various parameters and enabled some nodes while muting others…say, a single action button that eliminates all nodes from executing except the most basic setup for testing and experimentation.

**Comment by Trobinou** [comment]
You're right, especially as the pack is rich enough in nodes to do as I wish: [Mute / Bypass Relay] + [Fast Muter] or [Fast Bypasser] gives me complete satisfaction 👌 
I'm closing this request as it seems to me that there's no reason for it.

**Comment by Trobinou** [comment]
You're right, especially as the pack is rich enough in nodes to do as I wish: [Mute / Bypass Relay] + [Fast Muter] or [Fast Bypasser] gives me complete satisfaction 👌 
I'm closing this request as it seems to me that there's no reason for it.

**Comment by aegis72** [comment]
I still think that the "floating menu" aspect of this should remain. One of the issues is that, as the WF gets big/complex, if the user has to do a lot of settings located in different places. It would be REALLY cool iif there could be a "floating group," that maintained its position and Z-ordered to the top, where one could place commonly needed elements---seed control, pos/neg conditioning, and switches (fastbypass/mute, etc). That way, the user could set most settings in one spot that they use while experimenting around, and just keep a nice big preview window to view results.

On a different note, a node that simply showed the currently executing node and its progress/state (ie, % done and green running / purple failed) would be awesome to place in a floating group like that.
