### ISSUE TITLE
Adding one of several node types, including Label, Bookmark, & Fast Bypasser, node breaks the canvas

### ISSUE THREAD

**Issue by soulctcher** [rgthree/rgthree-comfy#331]
On a fully up-to-date system as of this posting, adding one of the following nodes freezes the canvas:

- Bookmark
- Fast Actions Button
- Fast Bypasser
- Fast Groups Bypasser
- Fast Groups Muter
- Fast Muter
- Label
- Mute / Bypass Relay
- Mute / Bypass Repeater
- Node Collector
- Node Combiner
- Random Unmuter
- Reroute

The effect of doing so is causing a recursive canvas to display as you can see in my image below. Toward the bottom left, you'll see a fresh bookmark placed on the canvas. After placing the node, the canvas completely freezes and is only visually responsive to right clicks. (It will respond to left clicks, but not visually. You can accidentally move or click on node settings while the canvas is frozen, but you cannot see the changes.) After reloading, you will see that the recursive canvas is visible below where the node label is.

![image](https://github.com/user-attachments/assets/f70a0a36-5fc3-4d5f-83d0-5de94390ba04)

This occurs even if every other add-on is disabled within ComfyUI; there is no conflict occurring with another node. See that here:

![image](https://github.com/user-attachments/assets/d8a266f7-ba93-4b5f-9440-05c6ab974a6f)

**Comment by soulctcher** [comment]
Looks like this was corrected with the following commit on the Comfy side:

[a08ec19](https://github.com/Comfy-Org/ComfyUI_frontend/commit/a08ec196c75395aa13232c7338423e4533172044) Fix frontend-only node freezing litegraph (#817) - huchenlei

**Comment by camoody1** [comment]
I'm having this same issue as of early morning 9/20/2024. Everything is up to date in my Comfy. If I disable the RGThree node package, the gui works fine. As soon as I re-enable it, the lockup happens again.

**Comment by rgthree** [comment]
Can someone file a bug with Comfy FrontEnd? Sounds like they may have broke something and I won’t be able to look into it soon.

**Comment by camoody1** [comment]
> Can someone file a bug with Comfy FrontEnd? Sounds like they may have broke something and I won’t be able to look into it soon.

@rgthree Today's Comfy update resolved this issue. I have closed the other ticket that I opened.
