### ISSUE TITLE
Thank you for your dedication, but there was a problem after the update that lable did not display properly. Please check!

### ISSUE THREAD

**Issue by shumoLR** [rgthree/rgthree-comfy#332]
![image](https://github.com/user-attachments/assets/470e39d8-f260-44ee-bd83-d7ee29543c06)
The above is an error problem, the original effect is as follows:
![image](https://github.com/user-attachments/assets/5296cb7e-ccd4-4d3a-bc68-9311cd56b2c6)
What is the mistake?

**Comment by upboy-web** [comment]
同样的问题，一直没解决

**Comment by rgthree** [comment]
I'm not sure exactly what is going on, but my guess is there's another extension that is doing something incorrectly with translations (as we've seen this before with other translation extensions)

**Comment by rgthree** [comment]
Marking duplicate of #334
