### ISSUE TITLE
Placing a Bookmark Node into my Workflow Causes GUI Canvas to Freeze

### ISSUE THREAD

**Issue by camoody1** [rgthree/rgthree-comfy#337]
As the title says, when I place an rgthree Bookmark into a workflow, the entire Comfy canvas locks up and I am unable to move around the screen, zoom, or click on any nodes. Without the bookmark, the workflow runs fine.

Earlier today (9/19/2024), everything was fine. When I came back later in the night, it was no longer working.

Initially, I thought it was the entire rgthree node pack, but I was able to narrow it down to just the bookmarks (as far as what I am using) that causes my issues. I am able to still use rgthree Image Compare and Power Lora Loader nodes without issue.

**Comment by JorgeR81** [comment]
I have the same issue.

**Comment by rgthree** [comment]
Can someone file a bug with Comfy FrontEnd? Sounds like they may have broke something and I won’t be able to look into it soon.

**Comment by JorgeR81** [comment]
This was just fixed in ComfyUI Front-end version: 1.2.60

https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.2.60

**Comment by camoody1** [comment]
> This was just fixed in ComfyUI Front-end version: 1.2.60
> 
> https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.2.60

I confirm that today's Comfy update seems to have resolved the issue. Closing this ticket, now.
