### ISSUE TITLE
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

### ISSUE THREAD

**Issue by S0LTIS** [rgthree/rgthree-comfy#338]
![image](https://github.com/user-attachments/assets/9b1b7a19-5c67-4db0-ba19-48be7632846b)

Will there be any chance this can be fixed? I have a gtx 1660 super 6gig, and this optimized recursive execution helped speed up my generations. Now I'm stuck at sitting for 5 mins per generation... please fix or update?

**Comment by rgthree** [comment]
Hi. Really, I should remove this message. There is no fix, the updated ComfyUI's execution from a couple months no longer needs the optimization (which is why it's forced off).

**Comment by S0LTIS** [comment]
Ok, I'll be sure and remove the node. Thanks.
