### ISSUE TITLE
Progress bar is not compatible with the new 1.3.x frontend

### ISSUE THREAD

**Issue by LukeG89** [rgthree/rgthree-comfy#339]
After updating to the latest frontend release (currently at 1.3.1), the progress bar doesn't show up if set at top and goes over setting button if set at bottom.

https://github.com/user-attachments/assets/8172b2ce-ed35-4816-93fd-2eaa227d2cf5

**Comment by rgthree** [comment]
Sounds like ComfyUI broke this. Can you file a bug with ComfyUI Frontend, in not sure when I’ll be able to look into this. Thanks

**Comment by LukeG89** [comment]
@rgthree Yes, they revolutionized the frontend (again) and broke other plugins as well, like Resouce Monitor from Crystools.

I'll report the problem to them, but they'll probably ask me to open a bug report to you.

**Comment by rgthree** [comment]
Was able to fix this forward. Should be working in 1.3.x now.

**Comment by LukeG89** [comment]
Awesome! Thank you!
