### ISSUE TITLE
IMPORT FAILED?

### ISSUE THREAD

**Issue by Dibucci** [rgthree/rgthree-comfy#34]
Just downloaded your plugins for Comfy, I'm still new to comfy btw, and followed your instructions of the simple git pull but the import failed... here is what it shows in the console

Error:
[WinError 1314] A required privilege is not held by the client: 'F:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'F:\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to F:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: F:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
### ComfyUI Revision: 1487 [2381d36e] | Released on '2023-09-25'
INFO:comfyui-prompt-control:Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
INFO:comfyui-prompt-control:Weight interpretations available: comfy,A1111,compel,comfy++,down_weight,perp
INFO:comfyui-prompt-control:Normalization types available: none,mean,length,length+mean
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 92, in <module>
    rgthree_config_user = json.load(file)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy module for custom nodes: Expecting value: line 1 column 1 (char 0)

it says to copy the ComfyLiterals folder Manually? but idk what it means by that tbh cuz all I did was git pull... do I just re-download that folder from the git hub and put it in there or...?

**Comment by rgthree** [comment]
Ah, I think ComfyLiterals error is either separate or a red herring; rgthree-nodes doesn't use ComfyLiterals.

But there was an error to fix; I've fixed the issue for rgthree-comfy; please pull and try again (I'm not sure how ComfyUI-Manager handles pushes; hopefully it would install a fresh copy and not one from cache...?)

**Comment by Dibucci** [comment]
> Ah, I think ComfyLiterals error is either separate or a red herring; rgthree-nodes doesn't use ComfyLiterals.
> 
> But there was an error to fix; I've fixed the issue for rgthree-comfy; please pull and try again (I'm not sure how ComfyUI-Manager handles pushes; hopefully it would install a fresh copy and not one from cache...?)

idk what you did but
![image](https://github.com/rgthree/rgthree-comfy/assets/25534395/a2126805-d3f7-4488-91fe-52f4a8e1b1b1)


it broke like eveyrthing
![image](https://github.com/rgthree/rgthree-comfy/assets/25534395/c8f32898-0076-4e8b-bdf1-489fc594e09b)

the 2nd image should show nodes instantly but no

**Comment by Dibucci** [comment]
it loaded but everything broke

**Comment by Dibucci** [comment]
ima try removing ComfyLiterals. to see if that fixes it tho

**Comment by Dibucci** [comment]
I removed your plugin and everything came back so idk what you changed but ComfyUI didn't like it

**Comment by Dibucci** [comment]
whatever you changed disabled all plugins

**Comment by rgthree** [comment]
Haha, glad to know I can affect such change :)

Okay, 43d11c7 should fast fix it for now. Sorry for disruption. If you pull the latest and should be all set.

**Comment by Dibucci** [comment]
lol, I try it now, sorry it took a bit, was mowing the lawn

**Comment by Dibucci** [comment]
Ok, it seams to be working now

**Comment by Dibucci** [comment]
still find it funny you broke the entierty of comfyUI's coustom Nodes with a quick change to your code xD

**Comment by alexbofa** [comment]
Thank you
