### ISSUE TITLE
Canvas Freezing on Zoom out

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#346]
When zooming out, the canvas freezes. It's not a total freeze, as I can still access Comfy Manager. This is happening with Comfy v0.2.2 (~2 weeks old as of this writing), as well as HEAD. Disabling this node fixes the issue. I verified that this node is causing the issue, as I disabled all other nodes except Comfy Manager and this one, and I still got the issue. I was able to enable all my other nodes (skipping rgthree), and I'm not getting any freezing when zooming out.

**Comment by rgthree** [comment]
Seems to be working fine for me. But it's not impossible something erroneous could be happening if combined with another extension + rgthree-comfy. Have you tried with _only_ rgthree-comfy installed?
(For istance. Other have found issues with rgthree-comfy when SaltAI nodes are installed, and certain translation extensions, etc).

Also, now there's more than just "one version" of ComfyUI. If you open the new ComfyUI settings, and then click "About" you'll see both the `ComfyUI v0.2.2` as well as a specific ComfyUI_frontend version.

FWIW, what's working for me is both of ` ComfyUI v0.2.2-84-gd1cdf51e` and `ComfyUI_frontend v1.2.60`, but if you had configured your ComfyUI to use a newer version, it's very possible changes there are breaking rgthree-comfy.

**Comment by ghostsquad** [comment]
> I disabled all other nodes except Comfy Manager and this one, and I still got the issue

Version check:
![image](https://github.com/user-attachments/assets/e0e07977-03cd-4e56-b50e-4407c1b48e7d)

**Comment by ghostsquad** [comment]
I've updated ComfyUI to 0.2.3 and I no longer have this problem. Looks like it might have been a regression.
