### ISSUE TITLE
Cannot connect inputs to Math Expression node

### ISSUE THREAD

**Issue by jordancoult** [rgthree/rgthree-comfy#347]
This happens when I connect a float or an int to the inputs. 
![Screenshot from 2024-10-02 21-23-51](https://github.com/user-attachments/assets/00317912-30ae-4a73-8123-0b753cd6d77a)

**Comment by rgthree** [comment]
I don’t think this has anything to do with rgthree-comfy. Did you mean to file a bug for one of those two nodes (tinyTerraNodes or Pythongoss?)
