### ISSUE TITLE
Issues with startup

### ISSUE THREAD

**Issue by brumie** [rgthree/rgthree-comfy#35]
Hi, did the most recent commit cause issues with the startup?
![image](https://github.com/rgthree/rgthree-comfy/assets/10722486/249bfdf1-31eb-4f9d-aabb-8546d4219b7b)

**Comment by VGBenjamin** [comment]
Hello,
I also have an issue and I just fixed it locally.

I have just removed the following  line in rgthree_config.json and rgthree_config.json.default
`// COPY THIS FILE BEFORE MAKING CHANGES TO: rgthree_config.json`

To be honest I am not sure if that is the same issue but you could try it.

**Comment by rgthree** [comment]
There was a bug overnight, f418be3 should have fixed that, though you created this issue after that commit. Did you pull the absolute newest? Try pulling again and seeing if that fixes. I'm not sure if ComfyUI-Manager caches anything.

Also, @VGBenjamin f418be3 fixed that as well.

**Comment by Khazar123** [comment]
> There was a bug overnight, [f418be3](https://github.com/rgthree/rgthree-comfy/commit/f418be396be49fd61fb4c4abd4909171320b1213) should have fixed that, though you created this issue after that commit. Did you pull the absolute newest? Try pulling again and seeing if that fixes. I'm not sure if ComfyUI-Manager caches anything.
> 
> Also, @VGBenjamin [f418be3](https://github.com/rgthree/rgthree-comfy/commit/f418be396be49fd61fb4c4abd4909171320b1213) fixed that as well.

I also have this problem, I updated it through manager, checked manually with git pull and it just said "Already up to date"

**Comment by alexbofa** [comment]
Yes, I have the same error. Reinstalled again via **git clone**, the same thing remains
