### ISSUE TITLE
Minor bugs with `Import Individual Nodes Widgets`

### ISSUE THREAD

**Issue by LukeG89** [rgthree/rgthree-comfy#350]
I found a couple of minor bugs with the `Import Individual Nodes Widgets` feature.

## Restoring default names to imported nodes
When you drop an image on a node, the name is restored to its default.

https://github.com/user-attachments/assets/ff88ebd8-e3cc-45e0-aef1-c7bb076df699

----

## Warning when you drop models from Model Library
Model Library introduced a dropping feature as well: You can drop models on compatible loaders.

But it seems that your feature is "conflicting" in some way, and everytime you drop a model, this warning appears:
"`No exact match found in workflow. Would you like to replace the whole workflow?`"

You can either confirm or not, it doesn't matter: The model will be replaced as intended. This is more of an annoying thing.

https://github.com/user-attachments/assets/fc6ad99e-624d-4f7b-a856-8c52f3a08a4e

**Comment by rgthree** [comment]
Thanks for the report.
