### ISSUE TITLE
Node idea

### ISSUE THREAD

**Issue by robertvoy** [rgthree/rgthree-comfy#353]
Hey,

Using the image comparer (great node btw) gave me an idea, below is a mock-up:
![image](https://github.com/user-attachments/assets/dd0aa2c1-2f70-44c1-abd5-3bdb5496b86c)

Like tabs for your prompt, you can switch between them, and whatever tab you have active will output on execution. Maybe with an option to add more tabs via properties?

I've been using note nodes to save prompts and swap between them. A node like this would be great.

**Comment by rgthree** [comment]
You can do something like this now, though it's not a single node nor as elegant.

But, three separate text nodes (representing A1 A2 A3) could be hooked up to an Any Switch and then it's just un-muting the one you want (similar to selecting the "tab" would be in the mock).

With that said, I was thinking of an even more powerful Power Prompt that had several composer-like features in it for some point down the line. Thanks for the suggestion.
