### ISSUE TITLE
Feature Request: Filtering for Fast Groups Muter/Bypasser

### ISSUE THREAD

**Issue by da2el-ai** [rgthree/rgthree-comfy#354]
Hello, thank you for publishing this wonderful custom node.

I have a feature request: I'd like to request adding a filtering function based on group colors for the Fast Groups Muter/Bypasser.

As shown in this diagram, I'm using the Muter to select upscale sizes, 
and the Bypasser to toggle Inpaint and Controlnet on and off.

I try to match the colors of the groups to avoid mistakes, but I still make errors occasionally.

I believe adding a filtering function based on group colors to the Muter/Bypasser would make it an even more user-friendly node.

I would greatly appreciate it if you could consider this request.
![Screenshot - 2024-10-14 15 06 38](https://github.com/user-attachments/assets/161d3bae-0ab8-41a4-9a6f-7ff02230e3a4)

**Comment by rgthree** [comment]
You can already filter by color, or even title. It’s in the docs; both the main README of in the help dialog if you right-click the node and choose “🛟 Node Help”.

**Comment by da2el-ai** [comment]
I didn't know about this feature.
Thank you very much!!
