### ISSUE TITLE
logic issue  for  the  “Any switch”

### ISSUE THREAD

**Issue by cardenluo** [rgthree/rgthree-comfy#355]
![image](https://github.com/user-attachments/assets/b69cd5ce-ee38-48f7-bf64-fdabd9944f23)
![image](https://github.com/user-attachments/assets/36b71561-3673-4d2e-bac7-26fc9357ca17)
Does it only support switching between port 1 and port 2? It is recommended that the logical priority be from bottom to top, which is more in line with the sorting of additional process switching.

**Comment by rgthree** [comment]
Any Swotch works by choosing the first non-null, non-empty value.

Your first screenshot is using bypass, which passes the value along. Thus, the image is with an empty clip.

If you _mute_ that group, then the value will be empty, and it will choose the next non-empty value, which is the cat group.

**Comment by cardenluo** [comment]
Thank you, I get it .
