### ISSUE TITLE
Fast Muter not passing through second (third, etc..) values when first is turned off if input is primitive

### ISSUE THREAD

**Issue by Targren** [rgthree/rgthree-comfy#358]
I'm not sure if I'm using it wrong, or if I've found an edge case, or what. I'm trying to set up a switch where I can swap out negative prompts based on some toggles, and this seems to be the closest I could come, if I could get it to work, but whenever I turn off the "top" (first) option,  it throws "CLIPTextEncode.encode() missing 1 required positional argument: 'text'" at me.   If I turn it back on, it takes the first option as expected. 

Rather than throw my whole messy workflow at you, I reproduced the problem by modifying the default galaxy bottle slightly.  Turn off the "Default Prompt" option, and try to queue it, and I get that error. 

User error? 

![ComfyUI_00001_](https://github.com/user-attachments/assets/25bed185-6efc-4252-833a-61e9eb0aaa8c)

**Comment by devocalypse** [comment]
From my understanding FastMuter is not supposed to pass a value at all on the opt_connection and while it passes only the first if enabled - it looks more like a bug, than a feature, which fools us to think it might work as an any switch but it does not.

The FastMuter itself can be used to mute the nodes connected to it manually but that's as far as it goes.
The OPT_CONNECTION output is used to connect to a repeater or action button which can command the whole muter to mute or enable all nodes connected to its left side.

Currently if you need only one path (option) you can use an any switch like in the attached example.
[FastMuter-Sample.json](https://github.com/user-attachments/files/17527924/FastMuter-Sample.json)

However if you need more than one at the same time you need a concatenator to which we have another connection from each node. You can see how that works in the sample as well.
Right now it's sub-optimal and having too many fast muter options leads to a performance penalty as you need to connect each one of them a second time to another node.

I'd like to use this occasion to make a feature request for the fast muter to have **out_any** and **out_concat** (and a in_separator) connections which will make the node quite more capable than it is now.

At the moment I'm managing a flow with more than 100 options linked to fastmuter and concatenator which x2 make 200 connections on top of another 80 or so for processing and it is a complete mess. An out_concat will slash the needed connections in 2 and make the workflow run much more smoothly.

**Comment by Targren** [comment]
Okay, so I *was* using it wrong. Thanks. From the demo, it looks like the right way is to use the muter to "toggle" the inputs for the any switch.  Actually, just using one path at a time is the ideal - using a node that lets multiple be turned on at once is just what I was using because I haven't been able to find a single-option multi-way switch node, so the muter will work well enough.  I'm not sure what the feature requests you were talking about would enable, but if it leads to be able to toggle multiple other nodes (say the positive and negative prompts) with one throw, then I'd throw a +1 on that wishlist.
