### ISSUE TITLE
Relay and Repeater seems broken in Latest comfyui (not beta)

### ISSUE THREAD

**Issue by ShalolaAuthor** [rgthree/rgthree-comfy#362]
i put relay with unconnected input in Group A connect it to the repeater input in Group B.

expected behavior: when group A got bypassed by group bypasser. it also turn Group B off.

what happens: when group A got bypassed by group bypasser. only group A got turned off.

0.2.6 works fine. problem starts at 0.2.7

**Comment by rgthree** [comment]
Do you use and have also updated the Use Anywhere extension? The latest breaks repeater, relay and other nodes from working correctly, see: https://github.com/chrisgoringe/cg-use-everywhere/issues/244

**Comment by rgthree** [comment]
0.2.7 works for me when I've disabled cg-use-everywhere, so I'm going to close this.
