### ISSUE TITLE
power prompt lora prompt found and  loaded problem

### ISSUE THREAD

**Issue by xueqing0622** [rgthree/rgthree-comfy#37]
There are the problem when I load some lora ( It found the another lora even have right path):

> 

🛈  rgthree Power Prompt:  Found "Cloth\Rich.safetensors" for "XQ\ziedRichDota2d" in prompt
✓  rgthree Power Prompt: Loaded "Cloth\Rich.safetensors" from prompt
🛈  rgthree Power Prompt:  1 Loras processed; stripping tags for TEXT output.

**Comment by rgthree** [comment]
Yea, that doesn't seem right. Made the matching a bit stricter, and also checked for more exact matches before iterating to find a loose match.

**Comment by xueqing0622** [comment]
Thx, it work!
have a nice day
