### ISSUE TITLE
Power Lora Loader "Add Lora" button not working anymore after latest ComfyUI frontend changes

### ISSUE THREAD

**Issue by Talae06** [rgthree/rgthree-comfy#375]
As stated in the title, the Power Lora Loader node's "Add Lora" button doesn't do anything anymore. When clicked, the color changes to light grey, indicating the input was received, but nothing happens. The other functionalities of the node seem to be working fine.

I realized this while using my own complicated workflow, then tried with a clean workflow (nothing except that node), and then verified the problem wasn't a conflict with some other custom nodes by disabling them all except for yours and ComfyManager. I also tried with both Firefox and Chrome just in case.

I tried downgrading ComfyUI to some older commits, to no avail. And ended up finding that the problem seems to be in recent changes to the frontend, because launching the latest backend version (156a28786be9ba6352061090096462bfb1b485bb), but with the argument "--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest" works fine. Launching without any argument of that kind works fine too. But using "--front-end-version Comfy-Org/ComfyUI_frontend@latest", as I was, breaks the "Add Lora" button.

The changes must be recent, since I seem to remember it working fine like a week ago or so, even with the then latest frontend version.

**Comment by LukeG89** [comment]
Yeah, 1.4.3 frontend broke it, this PR could be the culprit:

- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1556

@webfiltered Am I right?

**Comment by GalaxyTimeMachine** [comment]
I cam here to report the same problem. Reverting to other lora loaders until this is fixed.

**Comment by rgthree** [comment]
Thanks for the reports; that’s unfortunate.

As @webfiltered mentioned, you can use a previous, working frontend when starting ComfyUI until I can take a look.

**Comment by alessandroperilli** [comment]
@webfiltered this is a great occasion for me to say: "Hey, why don't we have the version of the front end selectable from *inside* the ComfyUI interface, so we can switch between them by simply refreshing the browser instead of relaunching the process? It would greatly simplify the debugging process."

I'm dreaming, I know.

**Comment by FleetingOrchard** [comment]
@alessandroperilli, that's not feasible without really substantial infrastructural changes.

**Comment by rgthree** [comment]
@webfiltered Looks like quite a breaking change here; Is it meant that widgets would no longer get all mouse events (specifically a `pointerup` event for this issue)?

There used to be a LiteGraph method called `processNodeWidgets` which passed the event the `widget.mouse` method for pointer events. But now, that method appears to be gone. There's a `processNodeClick` which is not even called for a pointer up, let alone not passing `up` events to the widgets.

What's the migration plan here?

**Comment by rgthree** [comment]
Filed https://github.com/Comfy-Org/litegraph.js/issues/341

**Comment by LukeG89** [comment]
I confirm that the button works again in 1.4.11! 🎉

**Comment by wouterdebie** [comment]
The "Add Lora" button works, as do the inputs to select a lora, but double clicking on the strength doesn't open the input to provide a number it seems. The arrows to set the numbers work though.

**Comment by wouterdebie** [comment]
It works! Thanks!

**Comment by Kadah** [comment]
Add lora button works, but direct number input (click number, get input to type in number) no longer works as of a Comfy change within the last 24 hours.

**Comment by Kadah** [comment]
> The `About` screen under `Settings` shows version information. If you're using a frontend version below 1.4.13, it is likely the issue is already fixed.

I am running 1.4.13

Minimal repo:

1. Fresh Python 3.10.15 environment
2. Fresh ComfyUI install from 82c53085616252e483a78abceac3b7e23495e019,  ComfyUI v0.3.5-10-g82c5308, ComfyUI_frontend v1.4.13
3. Install ComfyUI-Manager 76b073c3668224cdbb7e83203e81ba4fb2196771
4. Install rgthree-comfy 6d22bbf4508734a632f2fe9bcac5837bcd191abf
5. New blank workflow
6. Drop in Power Loader node
7. Add lora and try to edit value via popup input, cannot

[Unsaved Workflow (2).json](https://github.com/user-attachments/files/17954961/Unsaved.Workflow.2.json)

Able to repo on both Firefox 132.0.2 and Chrome 131.0.6778.85.

**Comment by JorgeR81** [comment]
> I am running 1.4.13

Try the latest frontend version ( 1.5.1 )

It's working for me.

**Comment by JorgeR81** [comment]
> If you must use 1.4.x for some reason,

The front that ships with Comfy it's always behind, by a few versions.
We need an extra cmd to get the latest one.
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#frontend-development

I think this is to prevent bugs in the "mainstem" version, but it also delays fixes.

**Comment by JorgeR81** [comment]
> 1.4.13 is in the ComfyUI core repo.

I just launched ComfyUI, without any extra cmd, I 've got `1.3.44`

How did you get the `1.4.13` ?

![x1](https://github.com/user-attachments/assets/0d1bed3a-34c7-4db8-9ef6-d090ca026ed0)

**Comment by rgthree** [comment]
Thanks @webfiltered for the fast fixes.
