### ISSUE TITLE
please help i'm going crazy

### ISSUE THREAD

**Issue by 4lt3r3go** [rgthree/rgthree-comfy#382]
First of all, thank you for all your amazing job on the nodes.
and man i'm really sorry to bother here but i'm really going crazy to try solve this.
Sorry again, I don’t khow were to contact you.
tryed to use any switch and muter but coudnt achieve what i'm looking for.

I’ll try to explain as briefly as possible.

With all the video models available, some of them have the start and end frame functionality, like COGs.
The problem is that the existing image switchers don’t allow leaving an empty option.
Let me give you an example: if I want to select an image to be used as "end frame" picked from a series of images, I can use the image switcher. But if I don’t want any end frame (so give freedom to the model to end as he want) and thus leave the switcher unconnected to an image, the switcher locks up and freeze the workflow from proceeding.

Do you have any idea how to solve this issue? all switchers do not allow to pass a null

![image](https://github.com/user-attachments/assets/a860b5e9-02ea-439d-9379-8d58a9e2a235)

i tryed fast muter but the image still pass through even if is muted 
![image](https://github.com/user-attachments/assets/02213803-d951-4fa8-83f0-3187b48b88d0)

this damn COG module need to have litterally NOTHING connected to the "end frame" point.
a reroute connected to nothiing is ok.

**Comment by 4lt3r3go** [comment]
i tryed fast muter but the image still pass through even if is muted 
![image](https://github.com/user-attachments/assets/02213803-d951-4fa8-83f0-3187b48b88d0)

this damn COG module need to have litterally NOTHING connected to the "end frame" point.
a reroute connected to nothiing is ok.

**Comment by JorgeR81** [comment]
You can use an `ImagePass` node, and connect the `Fast Muter` to that node, instead.

![pass](https://github.com/user-attachments/assets/0398e4b4-0440-4115-a97a-482d06f70725)

**Comment by 4lt3r3go** [comment]
> You can use an `ImagePass` node, and connect the `Fast Muter` to that node, instead.


yeah i just found now another passthrough that do the same thing but **image pass** is indeed more appropriate. ty🖤
now i need to control the muter externally, 
"convert widget to input" is not an option to comand "enable/disable" externally in MUTER.

any idea if this can be done?

**Comment by 4lt3r3go** [comment]
because i suck in coding, I tryed to modify the fast muter with an LLM, to add "convert widget to input" 
but obviously I Failed.

**Comment by 4lt3r3go** [comment]
I really don’t know how to thank you for all the time you took to answer my question—truly, I’m on my knees. 
What I actually needed was...well.. Let me explain.

if the muter (or anything that can accomplish the task) receives a specific value, let's say "1" or "true", 
then should be muted.
That’s why I was looking for a way to control it externally and transform the "enable/disable" option into a widget.

**Comment by 4lt3r3go** [comment]
i found a clumbsy workaround that do not require using it at all.
So dont loose extra time with me but hey, if you have a solution to this and is simple to type go on.
I will definetly use it

**Comment by JorgeR81** [comment]
> i found a clumbsy workaround, with extra kilometric cables and stuff that do not require using it.

I'm not sure about what you need ?

Do you want to connect another node to the `Fast Muter`?
Like it was a "normal" boolean widget ?

How would that help ?

![bool](https://github.com/user-attachments/assets/a4a57934-6f53-4662-a1fd-85d757df41af)

**Comment by rgthree** [comment]
I would just put the image it in a group, and use the Fast Group Muter to mute it when you don't want an end frame.

But I'm not familiar with all the other extensions JorgeR81 has recommended.

**Comment by 4lt3r3go** [comment]
Dear George and rgthree, 
you guys deserve statues and countless medals. 
I've been trying to solve this problem for a month without finding any solutions.
You were the only ones able to fix it.

I wish you lots of luck and an amazing career in life.

**Comment by 4lt3r3go** [comment]
i can't believe. i finished my workflow.
finally. i'm gonna cry now
![image](https://github.com/user-attachments/assets/805f0da3-4f26-44ad-b467-2ae525ee6b58)

**Comment by JorgeR81** [comment]
> I would just put the image it in a group, and use the Fast Group Muter to mute it when you don't want an end frame.

> unfortunatly, for some reasons, the image keep pass through even if is muted but Jorge solved that way

@4lt3r3go, in case it helps, you can also put the `ImagePass` in a group, and use `Fast Groups Muter`.

![g1](https://github.com/user-attachments/assets/9c2148eb-3051-4a9c-92fd-7a04ba28ec63)
