### ISSUE TITLE
[Feature Request?] Excluding Groups from Fast Groups Muter

### ISSUE THREAD

**Issue by jeffufu** [rgthree/rgthree-comfy#383]
Hello! Love using these suite of nodes to make it easier for me to make my workflows easier to use.

I use groups to help visually organize things, but sometimes it's not necessary to have them auto-populate the Fast Groups Muter node—you have to use the group or the workflow won't work. But in some parts of the workflow I've set it up so it's either or between two groups (manual prompting vs florence2 prompt) and this node makes it easy for people to make a choice. 

Is there a way to exclude certain groups?

Even better, is there a way to have different Fast Group Muter nodes that only include certain groups? So I could have different ones at different points that act like a switch in the workflow? 

Thanks for the hard work!

--edit: someone just told me about how to remove groups from this node, so consider my first question void now :)

**Comment by rgthree** [comment]
> Is there a way to exclude certain groups?

Yup. Sounds like you figured it out, but you can decide which groups can be included in the Fast Group Muter nodes' properties.

> Even better, is there a way to have different Fast Group Muter nodes that only include certain groups? So I could have different ones at different points that act like a switch in the workflow?

Yup. Just put two and use the aforementioned properties to include different groups for that node.
