### ISSUE TITLE
In the new Comfyui kernel, any switch of nodes fails with an error message

### ISSUE THREAD

**Issue by sky958958** [rgthree/rgthree-comfy#391]
In the new Comfyui kernel, any switch of nodes fails with an error message
![image](https://github.com/user-attachments/assets/627a2a19-7f5a-490b-a68e-89dd9cc5a691)

**Comment by amir84ferdos** [comment]
also, I have the same problem

**Comment by zewolf5** [comment]
With this console error:
"Return type mismatch between linked nodes: images, received_type(*) mismatch input_type(IMAGE)"

**Comment by amir84ferdos** [comment]
my problem is solved, just update your ComfyUI

**Comment by Dunc4n1dah0** [comment]
Confirmed, updated Comfy few hours ago - didn't work. Updated now - works.

**Comment by rgthree** [comment]
Bug in comfyui: https://github.com/comfyanonymous/ComfyUI/issues/5884
