### ISSUE TITLE
Unable to provide custom values on Power LORA Loader weights

### ISSUE THREAD

**Issue by CaptainGrock** [rgthree/rgthree-comfy#392]
Hi - with a recent update to Comfy, now it's not possible to click on the weight in the power lora loader to provide a more exact input into particular lora weights (you can only use the arrows to incrementally increase/decrease). Can you please fix this as being able to click on a value and just input for example "0.03" instead of having to click all the way down to a locked value of "0.1" would be very much appreciated.

![image](https://github.com/user-attachments/assets/0b9b9725-3f11-4ebc-88f0-8fb845ee8708)

Thanks!

**Comment by Wundrwaffle** [comment]
Confirm. After update same issue. Time consumption to click on arrows or trying to catch right number with scrolling.

**Comment by gonzalu** [comment]
me three :D

**Comment by artyfacialintelagent** [comment]
I bisected Comfy versions to find the problem. The error was introduced in Comfy frontend v1.4.3. I'm guessing this commit caused it:
https://github.com/Comfy-Org/ComfyUI_frontend/pull/1556

As a temporary workaround, downgrade the frontend to v1.4.2 by adding `--front-end-version Comfy-Org/ComfyUI_frontend@v1.4.2` to the Comfy start command (e.g. in run_nvidia_gpu.bat).

**Comment by gonzalu** [comment]
Unfortunately, they're up to 1.4.14 so lots has changed from 1.4.2 :( 

Hopefully get a fix from RGT or a fix in FrontEnd soon...

**Comment by vmetternich** [comment]
> Confirm. After update same issue. Time consumption to click on arrows or trying to catch right number with scrolling.

Same here.... and i love that node so much!

**Comment by rokodasolo** [comment]
me four :D

**Comment by rgthree** [comment]
Hey all, ComfyOrg accidentally broke this and they've fixed it in ComfyUI_frontend v1.5.0.

It look like that's the next version is v1.5.0 so you should be OK after that. Until then, you can always designate which frontend version you want to use when you start up comfy. For instance, add ` --front-end-version Comfy-Org/ComfyUI_frontend@latest` to your command startup to use the latest front end version, or `v1.5.0` to use the next.

Yuo can see more info in this duplicate thread https://github.com/rgthree/rgthree-comfy/issues/375#issuecomment-2507584179 Thx
