### ISSUE TITLE
Individual values ​​enclosed in curly braces {} are ignored by Power Prompt (rgthree) - related to "dynamicPrompts" maybe?

### ISSUE THREAD

**Issue by adydeejay** [rgthree/rgthree-comfy#396]
> > > > K-O-N-B: I do want random one prompts in five of it:
{sitting|lie_down|squatting|standing|kneeling}
> > > >
> > > ltdrdata:  Previously, it worked on all textbox widgets, but since it caused many problems, now it can only be used on textbox widgets where the feature has been explicitly enabled.
> > >
> > [adydeejay](https://github.com/adydeejay) : Hi @ltdrdata . I recently realized that {blue|red|yellow} no longer works in Power Prompt (rgthree). Has this feature been removed from ComfyUI or rgthree node? How can I reactivate it? Or do I need to use something else?
> >
> ltdrdata: In that case, it's likely that Power Prompt hasn't been updated to accommodate changes in ComfyUI. It would be a good idea to ask about alternatives in the rgthree repo.
>

Following @ltdrdata's [advice](https://github.com/comfyanonymous/ComfyUI/issues/5602#issuecomment-2540154069), I'm posting here in the hope that I will find an answer regarding this feature that no longer works in Power Prompt (rgthree). Are there any alternatives? Thank you! 🙏

**Comment by rgthree** [comment]
Interesting. Happy to fix the comfy change for Power Prompt. Do you happen to know what needs to be done?

**Comment by adydeejay** [comment]
Maybe this will help you: https://github.com/comfyanonymous/ComfyUI/issues/3302#issuecomment-2066891165

**Comment by ltdrdata** [comment]
This issue is related to https://github.com/comfyanonymous/ComfyUI/commit/744ac944db24795881cf41fc4ea015e5ea07a444

**Comment by rgthree** [comment]
Thanks. This option is now added for all power prompt text widgets.
