### ISSUE TITLE
Muter/Bypasser nodes consuming lots of GPU time

### ISSUE THREAD

**Issue by Squishums** [rgthree/rgthree-comfy#397]
Hello, the bypasser, muter, collector, and repeater nodes are causing constant graph refreshes, which eat up a not insubstantial amount of GPU time.

It seems like the root cause is here. Each subclass of BaseAnyInputConnectedNode maintains its own promise triggering separate graph redraws.
https://github.com/rgthree/rgthree-comfy/blob/main/src_web/comfyui/base_any_input_connected_node.ts#L50-L61

Normally litegraph is only drawing as needed, and really doesn't seem optimized for frequent redraws. I'm not sure if there was a performance regression in litegraph, but still. Could this not be batched across all nodes, or to only trigger a draw when needed?

Reproduction steps:
- Turn on litegraph canvas info (fps)
- Make an empty workflow
- FPS number doesn't change -- no graph draws. GPU usage 0%
- Add a `Fast Muter (rgthree)` node and some other random node like Preview Image.
- Connect the random node to the OPT_CONNECTION slot
- FPS number changes due to graph draws. GPU usage 1-3%
- Copy paste the nodes a dozen times
- FPS number changing constantly. GPU crying at ~20% trying to render fewer than 30 nodes.

**Comment by rgthree** [comment]
I can't reproduce the FPS dip or GPU usage on my machine (3060) with hundreds of connected fast muter nodes. But I can rewrite the code to only mark dirty if something's changed during stabilization :)

Please pull the latest and see if that helps.

**Comment by Squishums** [comment]
Impressive turn around time, thank you. The latest version does fixes the issue.

I was experiencing the problem with just the rgthree extension installed given the reproduction steps. Considering your file hadn't been touched in ages, I wonder if the issue only mattered due to some performance regression in litegraph rendering. I don't remember it being a problem in the past, but I have no idea when become one.

Anyway, for future reference I was on Win7 / Chrome / latest comfy at time of posting (roughly bdf3937) / RTX 4080.
