### ISSUE TITLE
comfyui search become very long 

### ISSUE THREAD

**Issue by VinsiGit** [rgthree/rgthree-comfy#40]
Comfyui search become very long because the samplers get added to the search options this happens when I activate this node.
normal (without the node)
![image](https://github.com/rgthree/rgthree-comfy/assets/40694625/291bf353-7644-4a0c-b7e3-161b1d634523)

with the node
![image](https://github.com/rgthree/rgthree-comfy/assets/40694625/f067fd0a-87eb-45f5-92ab-c408abadc3f9)
![image](https://github.com/rgthree/rgthree-comfy/assets/40694625/f1259d40-ec16-4daa-aaee-71a4f6c5b4c3)

**Comment by rgthree** [comment]
Yea, so annoying. Comfy's type system kind backed these nodes in a corner. It happened to me before my nodes even and I've been meaning to fix it. (My nodes now also contribute too).

Made the fix, but it's just for the popup, which is better than nothing. Unfortunately we can't style the popup after clicking the select box.. but let's take what we can get.

**Comment by gerroon** [comment]
> Yea, so annoying. Comfy's type system kind backed these nodes in a corner. It happened to me before my nodes even and I've been meaning to fix it. (My nodes now also contribute too).
> 
> Made the fix, but it's just for the popup, which is better than nothing. Unfortunately we can't style the popup after clicking the select box.. but let's take what we can get.

What is the fix?
