### ISSUE TITLE
Odd error and reroute incompatabilities.

### ISSUE THREAD

**Issue by pennyvc** [rgthree/rgthree-comfy#5]
Getting an inability to plug rg3 reroutes into normal reroutes, makes converting old workflows over really fiddly.

Also this bug just happened on loading a workflow  and it dissapoints me that I might have to ditch rg3 just to run my workflow :< 
<img width="541" alt="Screenshot 2023-08-24 014201" src="https://github.com/rgthree/rgthree-comfy/assets/128430314/e47165c8-d081-48bf-943b-51364cdce71c">

**Comment by rgthree** [comment]
Makes sense. I haven't fully tested intertwining my reroute node with normal reroutes, but I did fix the error here and my workflow seemed to work after that. Pull a fresh copy and let me know how it goes.
