### ISSUE TITLE
Fast muter not working with Lora Stack

### ISSUE THREAD

**Issue by Erehr** [rgthree/rgthree-comfy#52]
![image](https://github.com/rgthree/rgthree-comfy/assets/13292573/74c285e9-b23d-4797-b632-6eae613aff7d)
In example above it works only if the first lora stacker is enabled. Enabling any other or any combination of multiple stackers are not working (or only applying first one if enabled). 

In fact when any stacker other than first is enabled the output is no longer lora_stack as shown by apply lora stack node throwing a warning 
![image](https://github.com/rgthree/rgthree-comfy/assets/13292573/9d31815f-9f13-45a6-81aa-bb6ef50e3704)

**Comment by rgthree** [comment]
Ah, the Fast Muter node only mutes / bypasses the connected nodes; it is not a switch itself. The `OPT_CONNECTION` output is for connecting to other nodes, like the Fast Action Button, etc.

However, you can still use Fast Muter with the Any Switch to correctly mute nodes (so they don't do work) and choose then first non-muted value.

Would be something like this:

![Screenshot 2023-11-06 210505](https://github.com/rgthree/rgthree-comfy/assets/476360/c3821789-ee75-4cb2-baf4-e59780da6334)
