### ISSUE TITLE
Node Disconnection from bypassers when used as a template (possible bug)

### ISSUE THREAD

**Issue by aegis72** [rgthree/rgthree-comfy#53]
![image](https://github.com/rgthree/rgthree-comfy/assets/118572301/9799e2c8-d7e9-4cdf-834a-2234d57e32b3)

The left side works as expected, but when I save this as a template, many of the effects nodes become disconnected from the bypassers, requiring a manual re-attachment for the bypasser to work again. At first, I put all the connections into a node collector, but then thinking that might be the issue, I hooked them right into the bypass repeater itself, which are connected to a "disable all fx" switches at the top, and then I also hooked them up so each effect can be bypassed/enabled individually.

All my reroutes are rerouteprimitive/pyssss versus native, as I read that disconnections can happen with the regular reroute.

When saved as a workflow, all is well - no issues. Only difference is that in the upper left, there's a connection point for an image, whereas in the full 'workflow" version, there's an Input LoadImage (The template version is designed to be chained, hence the difference).

Attached is the JSON from the Template if that helps.
[AegisFlow_MaskFX_Template.json](https://github.com/rgthree/rgthree-comfy/files/13275582/AegisFlow_MaskFX_Template.json)

input files:
![maskfx](https://github.com/rgthree/rgthree-comfy/assets/118572301/346672fd-c658-4aae-bf43-0997b81dbcc5)
![swimsuit_watercolor](https://github.com/rgthree/rgthree-comfy/assets/118572301/00496612-046d-4e88-b8fc-2af5798d4666)
![horizontal mask](https://github.com/rgthree/rgthree-comfy/assets/118572301/a6564592-1f5d-49a2-ac52-77429e3bd193)

**Comment by aegis72** [comment]
As a text, I went ahead and un-bypassed all the previously bypassed nodes, but it still drops all but two of the connections when saved as a template. For now, I've replaced the bypassers with a note explaining the possible issue.

![image](https://github.com/rgthree/rgthree-comfy/assets/118572301/4bae695e-bc4a-4f86-97c2-e6faef432a48)

**Comment by aegis72** [comment]
The latest workflow (with the bypassers removed) 
[AegisFlow_MaskFX_Template_bypassers_removed.json](https://github.com/rgthree/rgthree-comfy/files/13301553/AegisFlow_MaskFX_Template_bypassers_removed.json)

**Comment by aegis72** [comment]
It seems as if this is somehow fixed?

![image](https://github.com/rgthree/rgthree-comfy/assets/118572301/8f200ecd-5d32-46a7-af16-7bfa64f00347)

Any idea how that happened? was it in an update I just missed?

**Comment by rgthree** [comment]
Ah, this was probably fixed with https://github.com/rgthree/rgthree-comfy/commit/84cb989ca368e7482fc2c226a651e05c6ac4ab06 (and #76 probably could have been marked a duplicate).

Glad its working now!
