### ISSUE TITLE
Reverse in/out node layout makes pin labels disapper

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#58]
Is that a limitation of ComfyUI? Because the reverse layout capability is one of the most useful in the entire ComfyUI universe. But it's a bit hard to use in certain scenarios where seeing the labels is really important (e.g., Context and Context Big nodes).

**Comment by rgthree** [comment]
Yea, more specifically the LiteGraph.js library ComfyUI uses. The rendering of the inputs/outputs is too locked down to change (though, oddly, it did provide enough exposure to swap them). Trying to render the labels puts them outside the node on the side of the connection as if it were on the opposite side.

**Comment by alessandroperilli** [comment]
I'm afraid that engine won't be able to accommodate the needs of the ComfyUI community much longer. Thanks for the quick reply.
