### ISSUE TITLE
Fast Groups Bypasser Get Syntaxerror

### ISSUE THREAD

**Issue by BoosterCore** [rgthree/rgthree-comfy#64]
got prompt
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 472, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 598, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'class_type'
![屏幕截图 2023-12-02 183543](https://github.com/rgthree/rgthree-comfy/assets/73834045/390d5d25-5a66-46d1-8dc2-af5d3c35dc1d)

**Comment by alessandroperilli** [comment]
Same here.

**Comment by mcquenji** [comment]
I pulled the latest changes and I'm still getting the error. are there any logs you need me to send you?

**Comment by mcquenji** [comment]
This is the [workflow](https://github.com/rgthree/rgthree-comfy/files/13537241/wallpaper.json) I'm using; Error is the same as OP posted.

**Comment by mcquenji** [comment]
Hmm okay weird ... After installing [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager), the issue was resolved. I don't know why but it now works lol

**Comment by rgthree** [comment]
Hmm. I wonder if it wasn't fully up to date, and the ComfyUi-Manager updated it? Not sure.

Curious, when you say it was the same error as OP posted; just the "class_type" error, or also the "SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 50)" error?

(I've never seen that last one at all...)

**Comment by mcquenji** [comment]
Hmm could it be that ComfyUI-Manager auto updates from a different source? Because my local repo was up to date with the remote... I thought that maybe it installed some dependencies (as stupid as it may sound) that fixed the bug?

And yes, i was also receiving the json thingy error.

**Comment by BoosterCore** [comment]
Thank you very much, after the upgrade, it's working for me.
