### ISSUE TITLE
Is seed widget exists, no queue processing

### ISSUE THREAD

**Issue by tholonia** [rgthree/rgthree-comfy#67]
I just installed the node "Seed (rgthree)", and I see that if the node exists in the map, even if unconnected, then "Queue Prompts" does nothing.  There are no errors in the console, nothing gets written to the log.  When I delete the node from the map, everything works.  Any clues as to why this is happening?

**Comment by Davikar** [comment]
I have the same issue but with the Fast muter node. The seed node seems to work for me.

**Comment by mordbane** [comment]
Same issue here.  Updated to the latest 12-4 ComfyUI.  No matter what workflow I put it on, "Queue Prompt" does nothing.  Remove it and prompts queue.

**Comment by rgthree** [comment]
Odd. I'm not seeing it, I wonder if there's a conflict with another custom node. Seed I could see, but Fast Muter would seem odd.

Can any of you open the browser dev tools (usually F12) and:
- In the Console tab, let me know if you see any messages/errors popup, _specifically_ when you click "Queue Prompt"
- In the Network tab, let me know if you see a new request to `/prompt` when you click "Queue Prompt" (and any error information associated with it)
- If there are any errors (or messages) in your terminal when you click "Queue Prompt"

**Comment by mordbane** [comment]
![image](https://github.com/rgthree/rgthree-comfy/assets/4472440/a29ae028-cad5-4a61-a8ef-4f312a8b73eb)

Not seeing anything in Network.  No errors in terminal.

**Comment by rgthree** [comment]
Looks like ComfyUI broke a lot of custom nodes again. https://github.com/comfyanonymous/ComfyUI/commit/7f469203b7b4547f1d0f7113d18095334fa06a4d specifically.

If you go back to the previous commit, I believe it will work:

```
git reset --hard d19de27
```

**Comment by rgthree** [comment]
Merging into another #69 as a duplicate.

**Comment by mordbane** [comment]
Makes sense, I've been seeing some strange seed stuff with other nodes.
