### ISSUE TITLE
Breaking changes from comfyui

### ISSUE THREAD

**Issue by rgthree** [rgthree/rgthree-comfy#69]
Looks like the upstream change at https://github.com/comfyanonymous/ComfyUI/commit/7f469203b7b4547f1d0f7113d18095334fa06a4d broke thousands of workflows using rgthree-comfy. Seed and other nodes all break due to now missing an important node property that was available beforehand.

I can't seem to find the culprit yet.

In the meantime, you can move ComfyUI back a couple days before that bad commit went in.

```
git reset --hard d19de275
```

**Comment by wordbrew** [comment]
The seed widget is fucked. And I literally just released a workflow that uses it heavily. Talk about bad timing lol.

**Comment by rgthree** [comment]
Yea, this is unfortunate. I filed https://github.com/comfyanonymous/ComfyUI/issues/2193 but I'm not sure they'll fix it... The group nodes commit a couple days ago made a pretty fundamental change to an important method...

**Comment by rgthree** [comment]
Alright, I _think_ my latest changes may work around the change; pulling to the latest of comfyui and rgthree-comfy should be fixed now.

**Comment by cliffrowley** [comment]
Wonderful, thank you for your efforts!
