### ISSUE TITLE
Non-backwards compatible changes & tagging

### ISSUE THREAD

**Issue by sternd** [rgthree/rgthree-comfy#7]
Hey, thanks for your excellent work! Just recently (3hrs ago), you released some non-backwards compatible changes to the repo. That's fine and you can do what you want. Could you please tag your versions though so I can version lock this repo for my workflow?

**Comment by sternd** [comment]
Also, it looks like it's leaving behind "ghost" nodes in the workflow for the combiners. My workflow was updated to use the new collectors, but in reviewing the JSON it still has the combiners as well. In addition to that, even though they don't show in the workflow, the workflow fails due to having "missing nodes" for the combiners.

**Comment by rgthree** [comment]
Unfortunately, I can’t suppress the error ComfyUI hardcodes, but when the message is closed, everything should still be working as combiners we’re removed and replaced with collectors.

Was that not working for you? I’ll never purposefully break workflows.

**Comment by nicolasSinger** [comment]
I confirm that the last commit broke some workflows. 

This one was broken for example  : https://civitai.com/models/119528/sdxl-comfyui-ultimate-workflow

I revert to commit d4207625097be499297fce6414701aacabad83e8 to make it work again.

**Comment by rgthree** [comment]
@nicolasSinger what seems to be broken about that workflow? It's not using Combiner/Collector nodes, and seems to load fine for me (though I don't have all the other extension nodes installed as separate issues).

**Comment by rgthree** [comment]
Commit c19d219 fixes forward legacy support for Node Combiner. Workflows will no longer auto-update.

Issue mitigated. We'll move forward with a friendlier patch.

**Comment by rgthree** [comment]
And 3802964 should fix the issue now. Support for Node Combiner will exist, and a message and a context option to switch to the Collector is now present, for the user to opt-in.

**Comment by sternd** [comment]
Just verified with an already updated workflow (using collector) and a non-updated workflow (using combiner). Both are working with the latest commit. In testing upgrading from combiner -> collector (using right click menu), all nodes were able to convert without issue. Thanks for getting this fix out!
