### ISSUE TITLE
Broken workflow

### ISSUE THREAD

**Issue by Davikar** [rgthree/rgthree-comfy#71]
So I've got a problem with a broken workflow, and I suspect it's got to do with this extension.
It started after I restarted ComfyUI. The entire interface is unresponsive and looks like this:
<img width="1763" alt="image" src="https://github.com/rgthree/rgthree-comfy/assets/8229634/ce3deeb5-2af5-4023-858f-de14f34e3ec3">
I tried running the workflow fixer, it fixed 1 error, but that still didn't help.

I have this error message:
```
		"source": "window",
		"type": "error",
		"timestamp": "2023-12-08T17:51:34.084Z",
		"message": "TypeError\nCannot read properties of undefined (reading 'scale')\nTypeError: Cannot read properties of undefined (reading 'scale')\n    at RerouteNode.onDrawForeground (http://127.0.0.1:8188/extensions/rgthree-comfy/reroute.js:80:43)\n    at drawBadge (http://127.0.0.1:8188/extensions/ComfyUI-Manager/comfyui-manager.js:283:25)\n    at node.onDrawForeground (http://127.0.0.1:8188/extensions/ComfyUI-Manager/comfyui-manager.js:963:45)\n    at LGraphCanvas.drawNode (http://127.0.0.1:8188/lib/litegraph.core.js:8518:18)\n    at LGraphCanvas.drawNode (http://127.0.0.1:8188/extensions/core/snapToGrid.js:86:24)\n    at LGraphCanvas.drawNode (http://127.0.0.1:8188/scripts/app.js:1146:29)\n    at LGraphCanvas.drawNode (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:28:25)\n    at LGraphCanvas.drawNode (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:28:25)\n    at LGraphCanvas.drawFrontCanvas (http://127.0.0.1:8188/lib/litegraph.core.js:7801:22)\n    at LGraphCanvas.draw (http://127.0.0.1:8188/lib/litegraph.core.js:7716:18)\n"
```
and a bunch of these warnings:

```
	"source": "console",
		"type": "warn",
		"timestamp": "2023-12-08T17:51:34.145Z",
		"message": "LiteGraph addWidget(...) without a callback or property assigned"
```

Uninstalling the extension makes things work again.

Here's the workflow:
[Simple SDXL.json](https://github.com/rgthree/rgthree-comfy/files/13619555/Simple.SDXL.json)

Update: I uninstalled, replaced all reroute nodes with regular reroute nodes and then reinstalled. Now it seems to be working again. So my guess the issue is there.

**Comment by alessandroperilli** [comment]
Same. After the last ComfyUI git pull, all my nodes, of all types don't render correctly on screen and the workflow is frozen (aka you cannot drag and drop to pan). 

Removing the rgthree custom node folder loads the workflow correctly and the non-rgthree nodes appear as expected.

Differently from @Davikar, I'm not in the position of replacing all reroute nodes :)

**Comment by rgthree** [comment]
Hmm.. did ComfyUI break us yet again? I'll take a look

**Comment by rgthree** [comment]
@Davikar Oddly, I'm can't reproduce on my end with your workflow, butboth "Zoe - Depth Map" and "OpenPoseEditor" were causing errors in your workflow. [11c96b2](https://github.com/rgthree/rgthree-comfy/commit/11c96b2ba6d4f6b0a9c36746936433307d5c6eb4) should fix the error you pasted, but since I can't repro I can't tell if something else is happening. Would you mind trying to load your broken workflow again with the latest?

@alessandroperilli Were you having the same error? `Cannot read properties of undefined (reading 'scale') at RerouteNode.onDrawForeground (http://127.0.0.1:8188/extensions/rgthree-comfy/reroute.js:80:43)`? Obviously, pull and see if the recent commit fixes you, pls

**Comment by alessandroperilli** [comment]
It now seems to be working as expected. Thank you for the ultra-quick fix!

**Comment by Davikar** [comment]
@rgthree Yepp, it seems to be working fine now. 👍

Have to look into those other nodes. It's strange cause the depth map is working as far as I can see, although that entire section is muted by default. The openpose editor I think just complains if it's empty.
