### ISSUE TITLE
Bookmark nodes issue

### ISSUE THREAD

**Issue by Gerkinfeltser** [rgthree/rgthree-comfy#73]
These are a super great idea but I've run into one issue concerning them. Also a suggestion if you're interested. :D

1. Upon web-interface reload/workspace json loading, they don't seem to retain their designated key. They end up all being set to "1".
2. Is a graph zoom level option also possible for each?

Anyway, thanks for the nodes. So many great additions! Keep up the good work!!!

**Comment by rgthree** [comment]
Oh, good catch no the bug. And, yea, felt like we wanted a zoom option too. It's added! Thanks
