### ISSUE TITLE
Fast Bypasser not retaining multiple items in single node when saved as template

### ISSUE THREAD

**Issue by CaptainGrock** [rgthree/rgthree-comfy#76]
Hi - I've tried it a few times but when I've saved a bypasser with multiple elements (such as this screenshot) in a template:

![image](https://github.com/rgthree/rgthree-comfy/assets/142545094/e861c67e-e105-4f25-9d25-7f352c57522f)

When recalling that template, it only shows the single element that was saved to it (see screenshot 2)

![image](https://github.com/rgthree/rgthree-comfy/assets/142545094/2af9bbae-c6f1-4463-aa2c-b1ffa4f5307e)

I haven't seen this behavior with other node configurations being saved, so I thought I'd start with you first.  Thanks in advance for diagnosing/resolving.

**Comment by rgthree** [comment]
Interesting. Node templates work by cloning the nodes... but if you clone the fast-bypasser/muter, it starts with only one input like when creating something new, and therefore only one input gets connected in the template. Kinda silly for LiteGraph to assume a node doesn't handle its connections. I'll have to find a hack around it.

**Comment by CaptainGrock** [comment]
Ok thanks - yeah on current build it's still an issue but looking forward to a future release/fix. Happy New Year!

**Comment by rgthree** [comment]
Ah, the issue was on template saving, not loading. Unfortunately already saved templates will have the issue saved.
