### ISSUE TITLE
Display "Title" property on "Display Any" node

### ISSUE THREAD

**Issue by Arcitec** [rgthree/rgthree-comfy#77]
Thank you so much for creating "Display Any". It is one of the most useful nodes in the entire ComfyUI universe.

One thing is super annoying though. Its title is always "source". Just that. "source"...

It would be great if it was changed to display the actual "Title" property instead, so that it can be renamed. For example, I'm building prompts from various text pieces which gets mangled together and then debugged via your "Display Any" node. Both my positive and negative prompt debug views have the title "source". It's just... suboptimal. :)

I suspect that it would be some simple change in the ts/web folders to improve this. What do you think? :)

**Comment by Arcitec** [comment]
Upon skimming through https://github.com/rgthree/rgthree-comfy/blob/main/ts/display_any.ts, I noticed one thing though... It seems like you're using the Node Title to do some kind of special processing/serialization of that node to JSON? It says:

```js
if (nodeData.name === "Display Any (rgthree)" || nodeData.name === "Display Int (rgthree)") {
```

Hmm. Wouldn't it be safer to do a check against the internal name of the node (`RgthreeDisplayAny`) so that the Title isn't part of that processing at all?

And then it would hopefully be possible to display the user's custom title on the node itself somehow.

**Comment by rgthree** [comment]
Ah, yes, as you've seen in your edits, there's actually no Title shown to keep the node clean. However, you can rename that `source` label, which is actually the _input label_ which you can rename by right-clicking on the input circle connection and choosing "rename slot"

**Comment by Arcitec** [comment]
@rgthree Thank you so much. I didn't know that slots could be right-clicked to rename. That is the best solution. It keeps the compact look.

I can't live without your Display node. You save me so much debugging time since I don't need to print to console / alt-tab. It's also amazing for UI display of dynamic prompt generation. Thanks a lot again for creating it. :) :heart:
