### ISSUE TITLE
[Feature Request] Add the ability for a muted group in Fast Groups Muter to act as a bypass instead of cutting connections

### ISSUE THREAD

**Issue by Jellybit** [rgthree/rgthree-comfy#79]
I think it would add a lot of functionality to have a muted group be bypassed, so that connections all remain, instead of simply cutting all connections when disabled. Perhaps this should be an option. I was trying to create a string of LoRAs, and quickly disable whichever one I wanted, but it would then complain that the connection was severed when trying to queue the image. Because of this, I simply cannot use your easy switch to simplify things.

**Comment by rgthree** [comment]
There’s a separate node with the same functionality but for bypassing: Fast Groups Bypasser.
