### ISSUE TITLE
[Feature] XOR muter/bypasser

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#87]
This is a feature request for a combination of "switch" and "bypasser/muter". Essentially, if I have 3 options/inputs to choose from, but only 1 of them can be active at a time, I'd like to be able to toggle one on, and have the others be automatically toggled off.

**Comment by Rvage0815** [comment]
i'd love to se that too :) 👍

**Comment by rgthree** [comment]
Makes sense to me. I've added a new property to Fast Muter, Fast Bypasser, Fast Groups Muter, and Fast Groups Bypasser called "toggleRestriction" which can be optionally set to "max one" or "always one" which will cause the node to _attempt_ to restrict the number of widgets that can be enabled to when clicking a toggle.

Note, though, that when using "max one" or "always one" it is only enforced when clicking a toggle on the node. If nodes within groups are changed outside of the initial toggle click, then these restriction will not be enforced, and could result in a state where more than one toggle is enabled (or none are enabled even if "always one" was selected). This could also happen if nodes are overlapped with multiple groups.

This should be fine for nearly all normal workflows.
