### ISSUE TITLE
KeyError: 'saved_prompts'

### ISSUE THREAD

**Issue by Lin1031** [rgthree/rgthree-comfy#89]
I have reviewed the previous issues and updated the code to the latest version, but I am still encountering the same problem.
![image](https://github.com/rgthree/rgthree-comfy/assets/44975556/acb8acef-51d0-4337-b9c8-ced5f8e9ad24)

**Comment by rgthree** [comment]
Interesting, are there start up errors in the console?

You should see something like this at the top of messages when you start up comfyui:

```
Prestartup times for custom nodes:
   0.0 seconds: /opt/ComfyuUI/custom_nodes/rgthree-comfy
```

**Comment by Lin1031** [comment]
> Interesting, are there start up errors in the console?
> 
> You should see something like this at the top of messages when you start up comfyui:
> 
> ```
> Prestartup times for custom nodes:
>    0.0 seconds: /opt/ComfyuUI/custom_nodes/rgthree-comfy
> ```

![image](https://github.com/rgthree/rgthree-comfy/assets/44975556/c2f0fd60-a297-41ae-8a4e-62272115f9b8)
I have found that the plugin is starting, but the problem occurs when I access the webpage.

**Comment by rgthree** [comment]
You should see a message at the top where you enter the startup command as well, after “Prestartup times for custom nodes”

It’s this prestartup script that sets up the key you’re seeing the error for. While I can fix the error, a larger issue for you could be comfy isn’t running prestartup scripts for some reason.

**Comment by Lin1031** [comment]
> You should see a message at the top where you enter the startup command as well, after “Prestartup times for custom nodes”
> 
> It’s this prestartup script that sets up the key you’re seeing the error for. While I can fix the error, a larger issue for you could be comfy isn’t running prestartup scripts for some reason.

I didn't see the 'Prestartup times for custom nodes' entry, neither in the logs nor on the webpage. Perhaps it's because I'm using the latest version of ComfyUI, which might have affected the execution of the `prestartup_script.py` file. Is there a way to ensure that the `prestartup_script.py` file is executed during startup? This is my startup shell command:``` python main.py --listen --disable-cuda-malloc --lowvram --temp-directory /data/stable-diffusion-webui/image/temp --output-directory /data/stable-diffusion-webui/image/output --input-directory /data/stable-diffusion-webui/image/input```

**Comment by rgthree** [comment]
Hmm.. the latest ComfyUI still operates the same way; it actually collects all custom nodes' prestartup_script.py scripts and executes them.

Are you familiar with python? You could try debugging what's going in main.py around this line: https://github.com/comfyanonymous/ComfyUI/blob/2c4e92a98b8338f754855a0db7dce164945e366e/main.py#L22

Spcifically, the rgthree-comfy custom node path should exist in the `node_paths` there and, further, the `script_path` should exist down on line 32.

**Comment by Lin1031** [comment]
> Hmm.. the latest ComfyUI still operates the same way; it actually collects all custom nodes' prestartup_script.py scripts and executes them.嗯。。最新的 ComfyUI 仍然以相同的方式运行;它实际上收集所有自定义节点的prestartup_script.py脚本并执行它们。
> 
> Are you familiar with python? You could try debugging what's going in main.py around this line: https://github.com/comfyanonymous/ComfyUI/blob/2c4e92a98b8338f754855a0db7dce164945e366e/main.py#L22你熟悉python吗？您可以尝试调试 main.py 围绕这一行的内容： https://github.com/comfyanonymous/ComfyUI/blob/2c4e92a98b8338f754855a0db7dce164945e366e/main.py#L22
> 
> Spcifically, the rgthree-comfy custom node path should exist in the `node_paths` there and, further, the `script_path` should exist down on line 32.具体来说，rgthree-comfy 自定义节点路径应该 `node_paths` 存在于 there 中，此外，应该 `script_path` 存在于第 32 行。

Thank you very much for your help. I have successfully identified the problem. My `custom_nodes` were stored in a different directory, but the `execute_prestartup_script` function was accessing the default address of `comfyUI/custom_nodes`.

**Comment by CoraAI** [comment]
> > Hmm.. the latest ComfyUI still operates the same way; it actually collects all custom nodes' prestartup_script.py scripts and executes them.嗯。。最新的 ComfyUI 仍然以相同的方式运行;它实际上收集所有自定义节点的prestartup_script.py脚本并执行它们。
> > Are you familiar with python? You could try debugging what's going in main.py around this line: [https://github.com/comfyanonymous/ComfyUI/blob/2c4e92a98b8338f754855a0db7dce164945e366e/main.py#L22你熟悉python吗？您可以尝试调试](https://github.com/comfyanonymous/ComfyUI/blob/2c4e92a98b8338f754855a0db7dce164945e366e/main.py#L22%E4%BD%A0%E7%86%9F%E6%82%89python%E5%90%97%EF%BC%9F%E6%82%A8%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E8%B0%83%E8%AF%95) main.py 围绕这一行的内容： https://github.com/comfyanonymous/ComfyUI/blob/2c4e92a98b8338f754855a0db7dce164945e366e/main.py#L22
> > Spcifically, the rgthree-comfy custom node path should exist in the `node_paths` there and, further, the `script_path` should exist down on line 32.具体来说，rgthree-comfy 自定义节点路径应该 `node_paths` 存在于 there 中，此外，应该 `script_path` 存在于第 32 行。
> 
> Thank you very much for your help. I have successfully identified the problem. My `custom_nodes` were stored in a different directory, but the `execute_prestartup_script` function was accessing the default address of `comfyUI/custom_nodes`.

I got the same error, is there a way to fix it while keeping the costumed nodes path unchanged?
