### ISSUE TITLE
Image Comparer not comparing

### ISSUE THREAD

**Issue by alessandroperilli** [rgthree/rgthree-comfy#91]
Excited about this new node. Thanks for developing it and sharing it with the community. 
Are there limitations in terms of what nodes can pass the input? It doesn't seem to work in the following situation (or in any other situation in my system):

<img width="1033" alt="Screenshot 2024-01-02 at 10 46 19" src="https://github.com/rgthree/rgthree-comfy/assets/9775949/848600fb-5d8f-4a7d-915c-dd298e63a4b8">

**Comment by rgthree** [comment]
I bet it’s there, but Comfy didn’t make the node tall enough automatically. Try pulling the height larger.

**Comment by alessandroperilli** [comment]
Yep...
