### ISSUE TITLE
[Bug] Context input/output labels missing after layout is changed to Right -> Left

### ISSUE THREAD

**Issue by ghostsquad** [rgthree/rgthree-comfy#93]
Repro Steps:

1. Add node `Context (rgthree)`
2. Right click, select "Connections Layout", select "Right -> Left"

![image](https://github.com/rgthree/rgthree-comfy/assets/903488/604832c1-973d-4bb3-86a0-511cfc2e45b4)

**Comment by rgthree** [comment]
Yea, unfortunately LiteGraph (the graphing framework ComfyUI uses) really doesn't want us to have Right-to-Left support and, while I've hacked it in for the inputs, it doesn't render the labels correctly (puts them outside the node). So this is infeasible for now, with re-writing a core part of LiteGraph.
