### ISSUE TITLE
[Feature Request] Flip All Bypass All

### ISSUE THREAD

**Issue by Immac** [rgthree/rgthree-comfy#98]
![image](https://github.com/rgthree/rgthree-comfy/assets/3265190/4cbc36b4-5c8d-4f4a-adc7-319ca24c648e)
Could be useful for certain workflows.

**Comment by rgthree** [comment]
You mean like flip each widget's current state? (Like, all widgets that are on turn to off, and al that are off turn to on?)

**Comment by rgthree** [comment]
Sure, why not. done
